### ISSUE TITLE
grml2usb with two same flavor names

### ISSUE THREAD

**Issue by XaariraaX** [grml/grml#100]
Hello,

I use grml for testing different computer systems and therefore I created an USB memory stick with 4 different grml versions on it (in detail: grml 2011.05, grml64 2011.05, grml32-full 2014.11 and grml64-full 2014.11). This worked perfect without any issue.

Now I wanted to create an USB memory stick with 6 differend grml versions - the 4 ones mentioned above plus grml32-full 2017.05 and grml64-full 2017.05. Unfortunately grml2usb only looks for the flavor name ("grml", "grml64" for the older 2011.05 version; "grml32-full" and "grml64-full" for the newer 2014.11 and 2017.05 versions) and owerwrites existing images with the same flavor name. This happens if I use the single images (grml32-full and grml64-full) and the combined image (grml96-full).

The grml2usb command I used:

grml2usb /mnt/grml_2011.05.iso /mnt/grml64_2011.05.iso /mnt/grml96-full_2014.11.iso /mnt/grml96-full_2017.05.iso /dev/sdb1

The images of 2014.11 are copied successfully and then will be overwritten by the 2017.05 ones. After restart there are only the versions of 2011.05 and 2017.05 useable.

Is there a way to get this fixed? As a workaround: Is there a way to change the flavor name of an iso image?

Thanks a lot!

Best regards

XaariraaX.

**Comment by mika** [comment]
Hm, this would mean that we'd have to take the version into account when copying files around and IIRC also rewriting syslinux/grub configuration files, as the flavor name is part of the `live-media-path=` setting. I'm not sure how much refactoring this would require, I'd be more than happy to accept a patch for this though. :)

FTR, this should have gone towards https://github.com/grml/grml2usb/issues :)

**Comment by XaariraaX** [comment]
Oh, I'm sorry for that - I'm not very familiar with github.

I'll close this issue and open a new one in the grml2usb section. ( https://github.com/grml/grml2usb/issues/18 ).

Best regards

XaariraaX.

**Comment by mika** [comment]
@XaariraaX thank you! :+1:
