### ISSUE TITLE
grml-zsh-config: use compinit -i or allow to override via environment variable

### ISSUE THREAD

**Issue by Nowaker** [grml/grml#103]
People who use grml-zsh-config on OSX with zsh installed by brew in multi-user environment (two OS logins) will encounter this problem every time a new shell opens:

```
zsh compinit: insecure directories and files, run compaudit for list.
Ignore insecure directories and files and continue [y] or abort compinit [n]? ncompinit: initialization aborted
```

This is due to the fact zsh deems any site-function that's not owned by $USER unsafe - even if that "unsafe" user is part of the same group.

Adding `compinit -i` to zshrc fixes the problem.

```
    compinit -i -d ${COMPDUMPFILE} || print 'Notice: no compinit available :('
```

I propose one of these solutions:

1. `compinit -i ...`
2. `compinit $COMPINIT_OPTS ...`

The latter is probably better.

**Comment by Nowaker** [comment]
@ft Thanks a lot!

FYI - the way I currently load grml-zsh-config on my OSX is `source /path/to/zsh-grml-config` in my system-provided `/etc/zshrc`. I hope the style you come up with will be somehow compatible with this approach, and there is one way or another to pass a "parameter" to be used for compinit when sourcing the config. Thanks again!

**Comment by ft** [comment]
Should be fixed by 5f07a91fbbec4a in grml-etc-core. There's documentation included that explains how it works. Let me know if there's something, that's not working.

**Comment by Nowaker** [comment]
Thanks! Will check out :)

**Comment by Nowaker** [comment]
Commit link: https://github.com/grml/grml-etc-core/commit/5f07a91fbbec4a
