### ISSUE TITLE
Serial console on ttyS1 blocked by login prompt

### ISSUE THREAD

**Issue by MichaelEischer** [grml/grml#104]
### Software version
GRML64-full_2017.05 + netboot package

### Hardware
Some server system which uses ttyS1 for its "virtual serial port" which is accessible via the management interface. 

### Steps to reproduce the problem
1. Add `serial console=ttyS1` to the kernel command line in the pxeconfig which is included in the netboot package
2. Boot and wait until you see the login prompt

### Expected behavior
GRML allows access to a working terminal

### Actual behavior
A login prompt, which ask for a user+password. As by default grml locks all accounts, there's no way to login.

### Cause
GRML only provides an override for ttyS0 (see https://github.com/grml/grml-live/tree/master/etc/grml/fai/config/files/etc/systemd/system/serial-getty@ttyS0.service.d/override.conf ). Is there a reason not to override the `serial-getty@.service` template?

**Comment by mika** [comment]
Ah, good catch - sounds like a decent fix to take care via `serial-getty@.service`, thanks!
