### ISSUE TITLE
grml-live created iso does not boot on efi kvm/tiano-core

### ISSUE THREAD

**Issue by chymian** [grml/grml#105]
booting a grml-live created ISO (with zfs included) drops to grub-shell on libvirt/kvm efi boot (tiano-core).
I tried: stretch (stable) and buster (testing) both with grml_full and grml_small
I also tried booting the testing/latest downloaded from the grml site with the same result.

what works:
the grml64-full_2017.05.iso boots fine, which suggests that something in the build-process has changed since then.
booting the self-mastered ISOs on a bios-based VM workes fine.

build-environment: 
grml-live version 0.32.1 on stretch (KVM)

since these are my first steps with remastering grml, I might be missing something?

**Comment by chymian** [comment]
Addition:
I booted my laptop from an USB stick (where I put the ISO on it with dd) and it did an EFI boot.
when I setup the KVM to use the USB (via additional HD), it boots. even so with USB-Hostdevice forwarding.

that leaves only the EFI - CD-ISO boot as an problem.

**Comment by mika** [comment]
This *might* be related to what we saw in https://github.com/grml/grml-live/commit/bc4f02658ffa63a71ef1bc4f37ae3707ff580382

I've got a customer which also experiences this problem and I'm trying to track this down. It's definitely related to EFI boot.

**Comment by mika** [comment]
I can reproduce the problem e.g. with:

```qemu-system-x86_64 -bios /usr/share/OVMF/OVMF_CODE.fd -hda grml64-small_sid_build2511.iso```

The:

```
Reloc 0 block size 2756420659 is invalid
Relocation failed: Unsupported
Failed to load image: Unsupported
start_image() return Unsupported
```

failure message doesn't appear though. So this might be related to the modified secureboot support instead (see e.g. https://github.com/grml/grml-live/commit/c35a30b42bac4de7089f936d6917b246ade6d5c5).

**Comment by chymian** [comment]
sorry, I forgot to mention that my laptop runs on buster/testing.
```
apt-cache policy ovmf
ovmf:
  Installiert:           0~20180812.cb5f4f45-1
  Installationskandidat: 0~20180812.cb5f4f45-1
  Versionstabelle:
 *** 0~20180812.cb5f4f45-1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        300 http://httpredir.debian.org/debian sid/main amd64 Packages
```

the sipwise-link does not work for me (404). which version of ovmf is needed?

**Comment by mika** [comment]
Ah sorry, the sipwise one is internal only, that should have been https://github.com/grml/grml-live/commit/bc4f02658ffa63a71ef1bc4f37ae3707ff580382

See https://github.com/grml/grml-live/commit/8c2668bf55e917289d87d9f59f93763d019a32ca what works for me, the ovmf v0~20180812.cb5f4f45-1 boots fine with its `OVMF.fd` (see my `qemu-system-x86_64 -bios ovmf/usr/share/ovmf/ -vga qxl -hda grml.iso -m 512` cmdline in the commit). Doesn't this work for you?

FTR: I'm currently debugging this issue on Dell hardware, where it fails to boot as well as soon as the Secure Boot enabled Ubuntu GRUB bootloader is present. I think we need to default to non-secure-boot to get this working everywhere. :-/

**Comment by chymian** [comment]
mika,
ok, so we both working on the same OVMF version.

I'm using it from virt-manager only… :(
so what fails to boot is, when I attach the iso to a cd drive-device. like here:
```
qemu-system-x86_64 \
-drive file=/usr/share/OVMF/OVMF_CODE.fd,if=pflash,format=raw,unit=0,readonly=on \
-m 1024 -vga qxl   \
-drive file=/srv/files/linux/installer/grml64-full_testing_build2489.iso,format=raw,if=none,id=drive-ide0-0-0,readonly=on \
-device ide-cd,bus=ide.0,unit=0,drive=drive-ide0-0-0,id=ide0-0-0,bootindex=1 
```
Attaching it as HD/USB always boots, as stated above.
like this one:
```
qemu-system-x86_64 -drive file=/usr/share/OVMF/OVMF_CODE.fd,if=pflash,format=raw,unit=0,readonly=on  \ 
-m 1024 -vga qxl -hda grml64_eb8-buster-zfs_2018.10-4.iso 
```

In both cases, ***Secure Boot is off***, in the Tiano-Boot-Menu. 
`-> Device Manager -> Secure Boot Configuration -> …State: Disabled`

And since the boot ends at a `grub prompt`, I'm not sure that it has to do with secure-boot.

going further with grub:
```
grub> configfile (cd0)/boot/grub/grub.cfg
```
shows: 
```
error: file `/EFI/ubuntu/x86_64-efi/vbe.mod` not found
```

I don't know, whether this is relevant, since I'm not a pro in CD-Boot-Process…
Hope this helps and have a nice Weekend.

**Comment by mika** [comment]
@chymian do the current daily ISOs work for you? There we have Secure Boot disabled and it's supposed to work as-is.

**Comment by mika** [comment]
Oh and the current 2018.12-rc1 should work as well (as the upcoming stable release which is in the works right now), JFTR

**Comment by chymian** [comment]
@mika, at the moment I'm traveling and not able to test. I will do, when I have a reliable I-Net connection.
