### ISSUE TITLE
Simplify and unify checksum files for ISOs, netpackages,...

### ISSUE THREAD

**Issue by mika** [grml/grml#120]
This is related to https://github.com/grml/grml/issues/26

We have .asc, md5, sha1, sha256 and sha512 checksum files and we should reduce this to to only .asc and one (or max two) further checksum files. It should be consistent everywhere (ISO files, netboot packages,...) and properly documented on our website how to use those files.

**Comment by mika** [comment]
I just noticed the grml-rescueboot is relying on `$ISO.asc` files for verifying the ISOs.

Just uploaded the corresponding asc files for 2020.06 release (generated via `for f in grml64-full_2020.06.iso grml64-small_2020.06.iso grml32-full_2020.06.iso grml32-small_2020.06.iso ; gpg --output $f.asc --armor --detach-sig $f`).

We need to take this into consideration...

**Comment by xtaran** [comment]
Please also take into account that the current system with inline signatures of the hash sums causes warnings by `sha1sum -c`:

```
% sha1sum -c grml64-small_2020.06.iso.sha1.asc
grml64-small_2020.06.iso: OK
sha1sum: WARNING: 19 lines are improperly formatted
```

BTW, on https://grml.org/download/ solely the `.sha1.asc` files are referenced. E.g. https://mirror.de.leaseweb.net/grml/ shows that there are indeed many checksum files per image.

So from my point of view the `.md5` and `.sha1` files should be dropped. Those hashing algorithms re no more trusted, neither by APT, nor by GPG, nor by OpenSSH. Drop them — and make sure no other tool relies on them anymore.

Especially `grml-rescueboot` should be updated accordingly as these `.asc` files are currently only available for the deprecated `.sha1` files.

For the remainder, I'd suggest the following:

For each ISO image, provide two additional files:

* `$ISO.sha256` or `$ISO.sha512`
* `$ISO.sha256.sig` or `$ISO.sha512.sig` providing detached PGP signatures of the above mentioned files.

Not sure if SHA256 or SHA512 or maybe both should be used. Both are IIRC from the SHA2 family and as I understand, the sole difference is the length of the hash. I'm not aware of any currently practical difference with regards to creating collisions. This might change in the future, but it might also happen that the SHA2 family of hashes as a whole gets deprecated before the hash length actually makes a difference. :-)

Another common pattern on that subject is:

* Use a single hashsum file for all images, typically called `SHA256SUM` or `SHA512SUM`, and a detached PGP signature file `SHA…SUM.sig` for that.

This has advantages and disadvantages:

* Advantage: Way less files in the file listing of the download directory, less clutter
* Disadvantage: Users which don't download _all_ you ISO images (i.e. nearly every user) will have to provide the option `--ignore-missing` to the `sha…sum -c` command to not get a lot of "missing file" warnings.

**Comment by mika** [comment]
We clearly need to clean this up, the usage of `.sha1.asc` files with the `Hash: SHA256` in it quite often confuses users, just received one further related mail. :)

**Comment by mika** [comment]
Thanks for the feedback so far - especially to @xtaran! - I'm trying to tackle this for our new release which is WIP right now.

FTR, so far we provided:

* `$GRML_FLAVOUR_$VERSION.iso`
* `$GRML_FLAVOUR_$VERSION.iso.md5`
* `$GRML_FLAVOUR_$VERSION.iso.sha1`
* `$GRML_FLAVOUR_$VERSION.iso.sha1.asc`
* `$GRML_FLAVOUR_$VERSION.iso.sha512`
* `$GRML_FLAVOUR_$VERSION.iso.torrent`
* `grml_sources-$VERSION.tar.gz`
* `grml_sources-$VERSION.tar.gz.sha1`
* `grml_sources-$VERSION.sha1.asc`
* `grml_netboot_package_$GRML_FLAVOUR_$VERSION.tar.bz2`
* `grml_netboot_package_$GRML_FLAVOUR_$VERSION.tar.bz2.sha1.asc`

I suggest to instead provide only those files:

* `$GRML_FLAVOUR_$VERSION.iso`
* `$GRML_FLAVOUR_$VERSION.iso.asc` (grml-rescueboot relies on this via `http://download.grml.org/${isoname}.asc` and I don't want to break existing installations; generate the file via `gpg --output $ISO.asc --armor --detach-sig $ISO`)
* `$GRML_FLAVOUR_$VERSION.iso.torrent`
* `grml_sources-$VERSION.tar.gz`
* `grml_netboot_package_$GRML_FLAVOUR_$VERSION.tar` (no bz2 extension, this doesn't save us anything but just wastes time in (de)compression given that the included files are compressed already)
* `SHA256SUMS` (containing sha256 sums of _all_ provided ISO/netboot/sources files)
* `SHA256SUMS.gpg` (gpg signed version of `SHA256SUMS`, generated via `gpg --armor --detach-sign --output SHA256SUMS.gpg SHA256SUMS`)

We then also need to adjust URLS and instructions at https://grml.org/download/.

For the future we might keep approaches like https://github.com/aperezdc/signify + https://github.com/jedisct1/minisign (thanks to cstamas for reminding me about those!) in mind, so I don't feel like they are relevant yet, especially as Windows users might not have simple ways for verifying those.
