### ISSUE TITLE
Tab not showing hidden directories with globdots and zsh-autosuggestions enabled

### ISSUE THREAD

**Issue by duhok1** [grml/grml#129]
With `setopt globdots` enabled and using **zsh-autosuggestions**, TAB does not show hidden directories/files.

This is my `~/.zshrc.local`:
setopt globdots
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

However, **setopt globdots** would work by _disabling_ zsh-autosuggestions!

TIA

**Comment by mika** [comment]
@duhok1 I've no idea what `/usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh` is supposed to be and neither Grml nor Debian provides that file.

Wild guess, does switching the order work for you? Like:

```
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
setopt globdots
```

If not, I'd say you need to report this issue towards the maintainers of `/usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh`, there's nothing we can do about it within grml-zshrc AFAICT. :)

PS: https://github.com/grml/grml-etc-core/ would have been the proper repository, this repository is about tracking issues for our Grml releases :)
