### ISSUE TITLE
2018.12 fails to boot on Trekstor Surfpad / stalls after loading initrd

### ISSUE THREAD

**Issue by flohoff** [grml/grml#130]
Hi,

the Surfpad is a Atom Z8300 based system. Its 64bit but it seems the UEFI is 32bit. The 64 and 96 grml variants not even start loading anything. Using the grml32 is loads the grub, grub loads kernel and initrd and then the machine stalls directly after loading initrd. 

No output after Loading initrd...

Flo

**Comment by mika** [comment]
Is there any further output available if running in debug/failsafe mode (see GRUB menu)?
How much memory is available on the system?

**Comment by flohoff** [comment]
System has 2 GByte modulo GFX Memory - It mentions 1.9GByte on boot.

Starting in debug mode is the same. 

Loading kernel...
Loading initrd...

Flo

**Comment by mika** [comment]
So RAM limits shouldn't be the problem.
Are you aware of any Linux distribution that's able to boot on this system?

**Comment by flohoff** [comment]
I can boot a current KNOPPIX to a point - I need more kernel command line to make it "usable"

acpi=off nofb nodrm nomodeset

otherwise the screen turns blank after 30 seconds. I can boot a Debian netinst image.

Flo

**Comment by mika** [comment]
Thanks for info.

Which version exactly of the Debian netinst image are we talking about?

**Comment by flohoff** [comment]
The ones i tried:

firmware-9.8.0-i386-netinst.iso works
firmware-9.8.0-amd64-netinst.iso does not work (Does not even find a bootloader)
firmware-9.8.0-amd64-i386-netinst.iso works
KNOPPIX_V8.2-2018-05-10-EN.iso works in sense of booting - has other issues.

**Comment by mika** [comment]
@flohoff we just released Grml 2020.06 with a bunch of fixes, could you please check whether your issue still exists with the new release?

**Comment by flohoff** [comment]
I havent got access to the Hardware anymore so i guess closing this may be the best idea.

**Comment by mika** [comment]
Thanks for your feedback, closing hereby :)
