### ISSUE TITLE
AMD Geode LX Support  on GRML 18-12

### ISSUE THREAD

**Issue by LucN31-2** [grml/grml#136]
Hi,
Using GRML 18-12 32 bits (or newer) AMD Geode LX processor isn't supported event wrote in [FAQ](https://grml.org/faq/#requirements).
Due to kernel [Bug#917569](https://www.mail-archive.com/debian-kernel@lists.debian.org/msg113363.html) boot end on kernel panic (log attached)
This bug is present on [SID nightly build of grml](https://daily.grml.org/grml32-full_sid/latest/) (same kernel), not in [debian SID kernel](https://packages.debian.org/sid/linux-image-4.19.0-5-amd64).
Debian buster installer boot fine with newer kernel.
Is it possible to release newer version with last kernel ?
Thx
Luc.
[kernel_panic_grml-sid.txt](https://github.com/grml/grml/files/3467552/kernel_panic_grml-sid.txt)

**Comment by mika** [comment]
Thanks for the pointer towards https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917569, @LucN31-2!

Updating to latest 4.19 kernel version (4.19.65 as of today) or by going towards a more modern kernel version like 5.2.7 (as of today) is definitely something we will do for the upcoming Grml stable release. Maybe I can find some spare minutes and provide a fresh kernel version sooner, no promises though yet. :)

**Comment by mika** [comment]
Our current daily ISOs (https://grml.org/daily/) provide recent kernel versions as present in Debian:

![screenshot 2019-11-01T15:37:10](https://user-images.githubusercontent.com/115592/68032277-a0e6a780-fcbd-11e9-8d33-4d5943506735.png)

I assume your issue is fixed hereby, @LucN31-2?

**Comment by mika** [comment]
I'm closing this one, assuming that this issue is fixed nowadays, given that our current daily ISOs are providing kernel >=5.4.0-4 from Debian.
