### ISSUE TITLE
Update Grml Kernel

### ISSUE THREAD

**Issue by jkirk** [grml/grml#139]
Decide whether we are going to use plain Debian Kernel or update our own grml-kernel.

**Comment by paulmenzel** [comment]
Kexec’ed Debian’s Linux kernel 5.3.7 (686) on Lenovo T60 without problems.

**Comment by mika** [comment]
We're using the Debian kernel since a few months in our current daily ISOs, and at least for now I don't want to maintain a Grml kernel package any longer, so closing this issue, deciding to use the Debian kernel in our public Grml ISOs.
