### ISSUE TITLE
not booting: fail to mount /dev/loop0 on /run/live/rootfs/grml64-full.squashfs

### ISSUE THREAD

**Issue by bernhardreiter** [grml/grml#141]
Official Grml 2018.12 (downloaded full with both variants) does not boot the live system from USB stick.

Error message is "Can not mount /dev/loop0 () on /run/live/rootfs/grml64-full.squashfs"

Grml 2017.05 worked with this stick on this machine before.

**Comment by bernhardreiter** [comment]
A `grml debug=1´ attempt to boot 64bit additionally shows

`SQUASHFS error: unable tp read xattr id index table`

**Comment by mika** [comment]
@bernhardreiter this very much sounds like a broken USB device or ISO, can you please verify checksum of the Grml ISO and try with another USB stick?

**Comment by bernhardreiter** [comment]
(resolved) It was a bad write sesssion to the usb stick.

The downloaded image signature was fine a fresh write on the stick resulted in a bootable one.
Thanks @mika!
