### ISSUE TITLE
gparted moving and resizing swap partition fails because it's occupied by GRML in the middle of the operation

### ISSUE THREAD

**Issue by 1ras** [grml/grml#143]
Hi,

moving and resizing a swap partition with gparted fails, because the swap partition is occupied by GRML in the middle of the operation.

It seems that the swap partition is occupied by GRML each time when the partition table is changed by gparted.

GRML 2018.12 full booted as amd64.

Thanks

Andi

**Comment by mika** [comment]
Hm, at least with a current daily ISO (see https://daily.grml.org/) I don't seem to run into this issue, WFM:

![screenshot 2020-02-10T15:32:21](https://user-images.githubusercontent.com/115592/74158575-9ae85700-4c1a-11ea-8d7a-34054505da80.png)

Can you please try with a current daily ISO or provide us more verbose steps how to reproduce this behavior?

**Comment by 1ras** [comment]
Unfortunately the system is back in production and I can't check right now, but I did a resize and move at the same time.

The swap partition was about 7 GB and there was 100 GB free space after the swap partition. I moved the swap partition to the end of the free space and resized it from 7 GB to 8 GB. This was done in one step (of course, gparted internally split it in multiple steps).

Start: |...|7GB-swap|100GB-free-space|...|
Goal: |...|99GB-free-space|8GB-swap|...|

**Comment by mika** [comment]
Would be also interesting, whether the bug still exists in our current stable release (2021.07)?

**Comment by allanlaal** [comment]
but you could swapoff and just use ram?

I moved grml under a separate /boot/grml partition, so I could resize the main /boot

everything worked: I duplicated /boot to a new location, I resized it, I deleted the old one. did not have any issues with 2020.06
the only mounted partition I needed was /boot/grml

**Comment by 1ras** [comment]
This was with a live boot of GRML, not with a fixed installation. Of course I initially made sure that no partition was in use by GRML, including the swap partition. But in the middle of the process GRML decided to use the swap partition. I guess somewhere in the middle of the process gparted made the kernel aware of a partition change and GRML said, "hey a new swap partition, let's use it".

I worked around the issue by only moving/resizing one partition at a time and after each step I had to run swapoff, as GRML reoccupied the swap partition.

Unfortunately I don't have access to this system anymore, but maybe I can try with GRML 2021.07 running on KVM.

**Comment by 1ras** [comment]
I was able to reproduce the issue with KVM and GRML 2018.12, but no longer with GRML 2021.07. It looks like this issue is already solved.

**Comment by mika** [comment]
That's great news, thanks for reproducing and your feedback in this issue, appreciated!

**Comment by 1ras** [comment]
Thank you for providing Grml!
