### ISSUE TITLE
grml64-full 2018.12: cannot install packages: dpkg: warning: 'ldconfig' not found in PATH or not executable

### ISSUE THREAD

**Issue by mirabilos** [grml/grml#144]
```
100|grml@grml:~ $ sudo apt-get install rdesktop                                
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libgssglue1
Suggested packages:
  pcscd
The following NEW packages will be installed:
  libgssglue1 rdesktop
0 upgraded, 2 newly installed, 0 to remove and 14 not upgraded.
Need to get 186 kB of archives.
After this operation, 531 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://snapshot.debian.org/archive/debian/20181230 testing/main amd64 libgssglue1 amd64 0.4-2+b2 [23.9 kB]
Get:2 http://snapshot.debian.org/archive/debian/20181230 testing/main amd64 rdesktop amd64 1.8.3-2+b1 [162 kB]
Fetched 186 kB in 1s (257 kB/s)                         
dpkg: warning: 'ldconfig' not found in PATH or not executable
dpkg: warning: 'start-stop-daemon' not found in PATH or not executable
dpkg: error: 2 expected programs not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin
E: Sub-process /usr/bin/dpkg returned an error code (2)

**Comment by mirabilos** [comment]
100|grml@grml:~ $ export PATH=/sbin:/usr/sbin:$PATH

before sudo works, so perhaps some `env_keep` issue?

**Comment by mika** [comment]
I can't reproduce this as user `grml`, who has `/sbin:/usr/sbin` inside $PATH by default, what shell are you using and how to reproduce this issue?

**Comment by mirabilos** [comment]
I typed `x` at the startup menu, then started an xterm from the windowmanager, then ran `mksh -l` to get a sensible shell.

Further debugging reveals that `/etc/profile` (as read by the `-l` option) resets `$PATH` to not include the supervisor binaries.

So this is a latent bug in the grml sudo configuration, hidden only by the (for Debian non-standard) presence of the sbin directories in the zsh configuration for the regular user?

**Comment by mika** [comment]
We ship the `/etc/profile` file as provided by `/usr/share/base-files/profile` from the `base-files` package, and also the sudo configuration is rather minimalist to stay as close to the defaults as possible.

What configuration change towards sudo configuration do you propose to fix this issue?

PS: please stop this passive aggressive communication style

**Comment by mirabilos** [comment]
Interesting. Yes, I can confirm that. Sorry for bad assumptions.

I have no idea why `sudo` would not set `$PATH` on grml. I do not have access to my regular system right now (PSU went bad), which is why I am on grml on a borrowed notebook; your best bet is, most likely, finding the piece in regular Debian that makes sudo set the PATH and see whether it is lacking in grml.

**Comment by mika** [comment]
So what e.g. Ubuntu (17.04 desktop live system is what I just had available) seems to be doing is providing the `sbin` directories within default $PATH (for the ubuntu user), and within `/etc/sudoers` they are using:

```
Defaults env_reset
[...]
Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
```

The sbin directories seem to be handled via `/etc/environment` and extended for `/snap/bin` via `/etc/profile.d/apps-bin-path.sh`, but this doesn't seem to be needed for us.
Instead it seems to be enough to just extend `/etc/sudoers` through the above mentioned two configuration lines. So for Grml we might want to add the following configuration lines to `/etc/sudoers`:

```
Defaults env_reset
Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
```

Any objections to that, @jkirk @formorer @ft @mirabilos?

**Comment by mirabilos** [comment]
This might even work without the `env_reset`, lemme test...

... yes, just adding the `secure_path` line on my running grml system fixes this issue.

Thanks for the quick response!
