### ISSUE TITLE
GPG signatures for grml 2020.06 missing on mirrors

### ISSUE THREAD

**Issue by michaellass** [grml/grml#151]
First of all, great to see a new release of grml! :slightly_smiling_face: 

It seems that the GPG signatures for the images are currently missing, i.e.:
* grml32-small_2020.06.iso.asc
* grml32-full_2020.06.iso.asc
* grml64-small_2020.06.iso.asc
* grml64-full_2020.06.iso.asc
* grml96-small_2020.06.iso.asc
* grml96-full_2020.06.iso.asc

Those are however linked in the download section of the web page, leading to a 404.

**Comment by mika** [comment]
Ouch, since that was part of javascript code we (well, myself! :)) missed this when switching from $ISO.asc towards $ISO.sha1.asc.
Thanks for reporting this @michaellass, it should be fixed now!
