### ISSUE TITLE
“Get Checksum/Signature” only contains deprecated SHA-1

### ISSUE THREAD

**Issue by Cigaes** [grml/grml#155]
On the Download page, the “Get Checksum/Signature” link points to https://download.grml.org/grml64-full_2020.06.iso.sha1.asc (or other variants), with only the SHA-1, but SHA-1 is considered really broken now. Please include more robust hashes in the most visible link.

**Comment by mika** [comment]
Thanks for reporting, we already have https://github.com/grml/grml/issues/120 regarding the checksum situation.

Just being curious: I don't really see the attack vector for the gpg signed file though (for the unsigned files it's clear of course and I fully agree that deprecated checksum methods shouldn't be used for unsigned files). Given that someone would need to have access to the according gpg key to create such a signature file (`.asc`), the used checksum method shouldn't really matter then, or am I missing something here?

**Comment by Cigaes** [comment]
Hi. If I understand how these collision work, if somebody can get control of a file that's included as is in the image, like a data file for one of the bootloaders, then they could craft it so that the SHA-1 you sign for the legitimate image would be the same as the SHA-1 of an image containing harmful changes. Or something along these lines at least. More a movie-plot threat, really, but today's movie-plot threats are tomorrow's state actors threats, and then they leak.

**Comment by mika** [comment]
Sounds like a pretty big challenge for an ISO file like the Grml ones, but I understand your concerns and we'll address them, thanks! :)

**Comment by mika** [comment]
So this was taken care of via https://github.com/grml/grml/issues/120, and I think the checksums we provide nowadays should be fine for everyone. If someone has any further suggestions, ideas for improvements,... please let us know! Thanks for your feedback, @Cigaes

**Comment by Cigaes** [comment]
Thank you. I think changing the signature file to cover the ISO file itself rather than a hash was the best choice indeed.
