### ISSUE TITLE
The bnx2x firmwares are missing from the initramfs

### ISSUE THREAD

**Issue by rfc1036** [grml/grml#160]
Hence, netboot fails on these systems. I have been able to fix this just by adding the content of /lib/firmware/bnx2x/ to initrd.img.

**Comment by mika** [comment]
Hm sounds like initramfs-tools' `manual_add_modules()` doesn't detect this dependency. I'm wondering whether we should fix this within Debian's (i-t) context or just unconditionally/always include `/lib/firmware/bnx2x` in Grml's initrd. Though it has disk usage of 3.8MB (firmware-bnx2x in unstable as of 2020-11-06), so we'd need to check how much bigger the initramfs would become then (@rfc1036 would you have a size comparison available for us?).

**Comment by rfc1036** [comment]
This is a regression since the precedent stable release, which used to work.

Indeed, all the bnx2x firmwares combined (there is one for each variant) are larger than 3 MB, and I agree that the current initrd.img is already quite large. But it contains firmwares for many other network cards, so I think that it should either contain all the popular ones (bnx2x is used by countless server models with 10GE ports) or none of them (since they are only needed for netbooting).

This would have been much easier if I were able to load multiple initramfs images, which I do in other cases with iPXE but did not work at all this time: the second image was apparently just ignored by the kernel and I have no idea about how to figure out why.
With multiple initramfs images it would be easy to keep initrd.img as is and then add a second image with the firmwares if needed, possibly optimized by only adding the ones which are actually needed.

Another problem is that ethdevice-timeout did not work, maybe because the interface does not appear at all? So I first did a lot of reboots before figuring out that the problem was the missing firmware (because the GRML boot process suppresses the kernel error messages at that stage!).

**Comment by mika** [comment]
@rfc1036 interesting, so this seems to be a change on the kernel side then.

The multiple initramfs images approach indeed would be very nice to have. For the time being I'll lookin into including bnx2x firmware by default in our initrd.

Regarding the `ethdevice-timeout`: it just controls the timeout within the execution of `ipconfig -t "$ETHDEV_TIMEOUT" "$dev"` (see https://github.com/grml/live-boot-grml/blob/master/components/9990-networking.sh#L95). So if the underlying device doesn't exist at all, I'm not sure how this should work? :) It's not like it would (try to) configure the device and then sleep for the specified timeout, but instead give the DHCP request enough time to finish. Or is your assumption from another side of things?

The "the GRML boot process suppresses the kernel error messages at that stage" also sounds like something should be changed, what boot options exactly are you using to boot your system via PXE/netboot?

**Comment by mika** [comment]
Alright, I managed to track this bug down:

```
root@grml ~ # lsinitramfs /boot/initrd.img-5.6.0-2-amd64 | grep bnx2x
usr/lib/modules/5.6.0-2-amd64/kernel/drivers/net/ethernet/broadcom/bnx2x
usr/lib/modules/5.6.0-2-amd64/kernel/drivers/net/ethernet/broadcom/bnx2x/bnx2x.ko

root@grml ~ # modinfo -k 5.6.0-2-amd64 -F firmware bnx2x
bnx2x/bnx2x-e2-7.13.15.0.fw
bnx2x/bnx2x-e1h-7.13.15.0.fw
bnx2x/bnx2x-e1-7.13.15.0.fw

root@grml ~ # ls /lib/firmware/bnx2x/bnx2x-e2-7.13.15.0.fw
ls: cannot access '/lib/firmware/bnx2x/bnx2x-e2-7.13.15.0.fw': No such file or directory
2 root@grml ~ # ls /lib/firmware/bnx2x/bnx2x-e1h-7.13.15.0.fw 
ls: cannot access '/lib/firmware/bnx2x/bnx2x-e1h-7.13.15.0.fw': No such file or directory
2 root@grml ~ # ls /lib/firmware/bnx2x/bnx2x-e1-7.13.15.0.fw
ls: cannot access '/lib/firmware/bnx2x/bnx2x-e1-7.13.15.0.fw': No such file or directory
2 root@grml ~ # ls -l /lib/firmware/bnx2x/ 
total 3193
-rw-r--r-- 1 root root 168680 Sep  1  2019 bnx2x-e1h-7.0.29.0.fw
-rw-r--r-- 1 root root 171920 Sep  1  2019 bnx2x-e1h-7.8.19.0.fw
-rw-r--r-- 1 root root 173016 Sep  1  2019 bnx2x-e1h-7.10.51.0.fw
-rw-r--r-- 1 root root 178984 Sep  1  2019 bnx2x-e1h-7.12.30.0.fw
-rw-r--r-- 1 root root 178992 Sep  1  2019 bnx2x-e1h-7.13.1.0.fw
-rw-r--r-- 1 root root 161368 Sep  1  2019 bnx2x-e1-7.0.29.0.fw
-rw-r--r-- 1 root root 163592 Sep  1  2019 bnx2x-e1-7.8.19.0.fw
-rw-r--r-- 1 root root 164392 Sep  1  2019 bnx2x-e1-7.10.51.0.fw
-rw-r--r-- 1 root root 170192 Sep  1  2019 bnx2x-e1-7.12.30.0.fw
-rw-r--r-- 1 root root 170096 Sep  1  2019 bnx2x-e1-7.13.1.0.fw
-rw-r--r-- 1 root root 289848 Sep  1  2019 bnx2x-e2-7.0.29.0.fw
-rw-r--r-- 1 root root 310440 Sep  1  2019 bnx2x-e2-7.8.19.0.fw
-rw-r--r-- 1 root root 321456 Sep  1  2019 bnx2x-e2-7.10.51.0.fw
-rw-r--r-- 1 root root 321320 Sep  1  2019 bnx2x-e2-7.12.30.0.fw
-rw-r--r-- 1 root root 320936 Sep  1  2019 bnx2x-e2-7.13.1.0.fw
root@grml ~ # dpkg -S /lib/firmware/bnx2x/
firmware-bnx2x: /lib/firmware/bnx2x
root@grml ~ # apt update
[...]
root@grml ~ # apt-cache policy firmware-bnx2x
firmware-bnx2x:
  Installed: 20190717-2
  Candidate: 20190717-2
  Version table:
 *** 20190717-2 500
        500 http://snapshot.debian.org/archive/debian/20200624 testing/non-free amd64 Packages
        100 /var/lib/dpkg/status
```

So the expected firmware files aren't shipped on the Grml stable version, the kernel package and firmware-bnx2x sadly don't fit to each other.

Workaround:

```
root@grml ~ # echo 'deb http://deb.debian.org/debian buster-backports main contrib non-free' > /etc/apt/sources.list.d/backports.list
root@grml ~ # apt update   
[...]
root@grml ~ # apt install firmware-bnx2x -t buster-backports        
[...]
```

Then the generated initramfs file includes the bnx2x firmware files:

```
root@grml ~ # lsinitramfs /boot/initrd.img-5.6.0-2-amd64 | grep bnx2x 
usr/lib/firmware/bnx2x
usr/lib/firmware/bnx2x/bnx2x-e1-7.13.15.0.fw
usr/lib/firmware/bnx2x/bnx2x-e1h-7.13.15.0.fw
usr/lib/firmware/bnx2x/bnx2x-e2-7.13.15.0.fw
usr/lib/modules/5.6.0-2-amd64/kernel/drivers/net/ethernet/broadcom/bnx2x
usr/lib/modules/5.6.0-2-amd64/kernel/drivers/net/ethernet/broadcom/bnx2x/bnx2x.ko
```

FTR, the current Grml daily ISOs are working fine already, they include the bnx2x firmware files as expected.

I will provide updated netboot packages and mention this bug in the list of known bugs of Grml 2020.06.

Thanks for reporting, @rfc1036!
