### ISSUE TITLE
GRML 2020.06 - sometimes is the boot sequence different

### ISSUE THREAD

**Issue by Jurij-Ivastsuk** [grml/grml#164]
Hello,
while experimenting with GRML 2020.06 I noticed the following: 
sometimes the boot sequence is different. The conditions of the tests are the same. It doesn't matter if you boot from the CD or if you boot an ISO-image in the virtual machine (VirtualBox), the behavior remains similar: 
sometimes the boot sequence is with: "Failed unmounting /run/live/medium.", sometimes without (see screenshots)
![without_Failed](https://user-images.githubusercontent.com/51372456/102793254-f0989e80-43a9-11eb-8e2b-b3a128da47f4.png)
![with_Failed](https://user-images.githubusercontent.com/51372456/102793256-f0989e80-43a9-11eb-900a-01824dbd7d30.png)

How can one explain such a behavior? Is this a feature or is this a bug?

**Comment by mika** [comment]
Well, there's no guarantee for a specific boot order, as things are started in parallel to get everything up and running as fast as possible.

You seem to be searching for https://github.com/grml/grml/issues/109, so marking this one as duplicated and closing, please followup in https://github.com/grml/grml/issues/109.
