### ISSUE TITLE
Boot hangs on AMD Renoir APU when loading amdgpu

### ISSUE THREAD

**Issue by michaellass** [grml/grml#165]
Trying to boot grml-full 2020.06 on a Lenovo Thinkpad T14s (AMD) just hangs forever. Booting the debugging variant shows that the system freezes at the following point:

```
fb0: switching to amdgpudrmfb from EFI VGA
```

As workaround, it is possible to boot with the `nomodeset` kernel argument. This will lead `amdgpu` to fail loading and never try to take over control.

The notebook contains an AMD Ryzen 4750U processor with integrated Radeon RX Vega 7 GPU (Renoir APU).

Searching the web for this error message shows that missing firmware files are one possible reason. However, the package `firmware-amd-graphics` is installed in the grml live ISO. So maybe it is just a matter of kernel/firmware being too old to properly support this hardware.

**Comment by michaellass** [comment]
I had another look at the installed package versions and I think it's just missing the firmware. I didn't realize that this APU uses different firmware to the normal Vega GPUs. According to the [Debian changelog](https://metadata.ftp-master.debian.org/changelogs//non-free/f/firmware-nonfree/firmware-nonfree_20200918-1_changelog), firmware for Renoir was included in version 20200421-1 of `firmware-amd-graphics`, however grml contains version 20190717-2.

I'll test again with one of the daily ISOs.

**Comment by mika** [comment]
Sorry for the late reply, just wanted to thank you for reporting in detailed and perfect way, also testing and closing the issue! :+1:
