### ISSUE TITLE
SyntaxWarning at grml2usb 0.17.0

### ISSUE THREAD

**Issue by mateusz-lacki** [grml/grml#166]
When calling:
grml2usb --bootoptions="persistence" grml64-full_2020.06.iso /dev/sdd1

the following warning pops up
/usr/sbin/grml2usb:1691: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if mbrcode is "":
Executing grml2usb version 0.17.0

system: Ubuntu 20.04

**Comment by mika** [comment]
Thanks for reporting this, this was already fixed via https://github.com/grml/grml2usb/commit/25c3bf7f43e285c2a6ab997a44efd8d21a514207, which was shipped with grml2usb v0.18.0 (and current version is 0.18.5).

(We don't have way how to push a grml2usb update to Ubuntu ourselves, though if someone can do this we'd appreciate this of course!)
