### ISSUE TITLE
git.grml.org Let's Encrypt HTTPS certificate expired July 3rd

### ISSUE THREAD

**Issue by secondfry** [grml/grml#170]
```
% curl -L https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc > ~/.zshrc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
<img width="432" alt="Screenshot 2021-07-06 at 17 08 49" src="https://user-images.githubusercontent.com/400605/124614385-d6716a00-de7c-11eb-92ea-b97cd2dce1bd.png">

**Comment by secondfry** [comment]
For time being one can use `https://raw.githubusercontent.com/grml/grml-etc-core/master/etc/zsh/zshrc` to install grml-zsh-config.

**Comment by secondfry** [comment]
Seems that it got fixed.

**Comment by mika** [comment]
@secondfry thanks for reporting this, we were indeed not aware of this issue and I just took care of it and will also add it to our monitoring so it doesn't happen again :) thanks again!
