### ISSUE TITLE
grml64-full 2020.06: /usr/bin/grml-x crashes with TypeError exception

### ISSUE THREAD

**Issue by datenwolf** [grml/grml#173]
When starting grml64-full 2020.06 with the extended bootloader option "Graphical" to boot directly to screen, it crashes with

```
  File "/usr/bin/grml-x", line 231, in <module>
    rc = main()
  File "/usr/bin/grml-x", line 208, in main
    f.write(XORG_CONF_HEADER + "\n")
  File "/usr/lib/python3.8/tempfile.py", line 613, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'

```

**Comment by datenwolf** [comment]
Screenshot of the issue reproduced in QEmu

![grml-crash](https://user-images.githubusercontent.com/292100/125449729-5af4249b-7392-45aa-9928-ff3d5a75b296.png)

**Comment by mika** [comment]
This should be fixed nowadays, can you please check whether it's working for you with our Grml 2021.07-rc1 release? See https://grml.org/download/prerelease/ + https://grml.org/changelogs/README-grml-2021.07-rc1/

**Comment by mika** [comment]
This is known as https://github.com/grml/grml/issues/152 and fixed with the new rc and stable release, closing hereby.
Thanks for reporting!
