### ISSUE TITLE
serial console=ttyS0 breaks several other boot options like ssh=, services= or netscript=

### ISSUE THREAD

**Issue by haidinger** [grml/grml#176]
**Describe the bug**
When running grml with the serial boot option and switching the "main" console to ttyS0 to see all boot messages on the serial connections, several boot options cease to work (have no effect). I guess this is due to the boot script relying on tty0 as the main console. Among those are notably (but not limited to):
-  ssh=
-  services= 
-  netscript=

The boot options are just ignored as if not specified. Most likely others are affected as well but those three explicitly don't work for me.

**Steps To Reproduce**
Boot grml and modify the boot options. Verified both when booting the ISO or via PXE (in KVM or Virtualbox as well as on a venerable AMD Phenom II).

Append the boot options: 
`serial console=tty0 console=ttyS0 ssh=grml services=haveged`

Note that the problem _only_ exists with console=ttyS0 being the **last** console option specified (as the last console= parameter defines the "main" console for output).
The order of the other boot options provided don't seem to have any influence on the behavior.

**Expected behavior**
Honor the boot options, start and configure ssh, haveged service and try to fetch and run what was specified by netscript.

**Screenshots**
ttyS0:
![ttyS0 console](https://user-images.githubusercontent.com/19545847/129753129-6ad6ce0a-0aac-4491-9cef-ce818ff1ae9a.jpg)
tty0:
![tty0 console](https://user-images.githubusercontent.com/19545847/129753160-37a5accb-a3dc-4cc7-b2b2-22be3ff0ea50.jpg)

**In which Grml Version did the bug occur?**
grml64-2021.07 and earlier releases.

Output of `grml-version`:
grml64-full 2021.07 Release Codename JauKerl [2021-07-25]

**Additional context**
Note that this is an old bug and probably buried deep in the startup scripts. I'm using grml as a PXE booted diskless machine on a headless server (hence the serial) for a *long* time (Eierspass, anyone?). With the release of 2021.07, I've finally taken the time to narrow down the origin.

**Additional program output to the terminal or log subsystem illustrating the issue**
Note that the password is **not** set for root or grml users despite the tty0 screenshot claims it is.
`root@grml ~ # egrep '^(root|grml):' /etc/shadow`
`root:*:18456:0:99999:7:::`
`grml:*:18833:0:99999:7:::`

Just in case anyone wonders howto use the serial console with Virtualbox and Putty, here are two screenshot (Virtualbox UI in German but I'dm pretty confident you'll manage...).
Note that's important **not** to have the checkbox selected for the pipe. If unchecked, the pipe will be created by Virtualbox but if checked it needs to exist already.
![virtualbox_serial](https://user-images.githubusercontent.com/19545847/129799104-fde4a3c8-fd82-4b7f-9961-e390370aa46b.jpg)
![putty_serial_pipe](https://user-images.githubusercontent.com/19545847/129799117-ee2eef0a-d78a-4179-a1b7-52421b46d48f.jpg)

**Comment by mika** [comment]
Thanks for the detailed bug report and steps to reproduce! :+1:

**Comment by hawaiik** [comment]
Ran into the same issue today as well. As an additional comment: We used 2018.12 before which didn't had that issue. But due to new hardware we had to update our rescue Image.
Is there any idea when this can get fixed?

**Comment by henning-schild** [comment]
```
● grml-autoconfig.service - Grml boot option support
     Loaded: loaded (/lib/systemd/system/grml-autoconfig.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2022-02-23 14:53:16 UTC; 4min 38s ago
    Process: 674 ExecStart=/etc/init.d/grml-autoconfig (code=exited, status=1/FAILURE)
   Main PID: 674 (code=exited, status=1/FAILURE)
        CPU: 2.395s

Feb 23 14:53:11 jupiter systemd[1]: Starting Grml boot option support...
Feb 23 14:53:16 jupiter systemd[1]: grml-autoconfig.service: Main process exited, code=exited, status=1/FAILURE
Feb 23 14:53:16 jupiter systemd[1]: grml-autoconfig.service: Failed with result 'exit-code'.
Feb 23 14:53:16 jupiter systemd[1]: Failed to start Grml boot option support.
Feb 23 14:53:16 jupiter systemd[1]: grml-autoconfig.service: Consumed 2.395s CPU time.
```

**Comment by mika** [comment]
I managed to reproduce the issue[1] (thanks  @madduck for the initial test system that made me look into it :)). When booting with `ssh=grml break=init` one can edit `/root/lib/systemd/system/grml-autoconfig.service` (before the system continues booting into systemd), and when replacing `StandardInput=tty` with `StandardInput=null` it works as expected.

[1] I used Virtualbox, booting a Grml ISO with the serial console boot menu entry (enabling `console=tty1 console=ttyS0,9600n8`).  Relevant Virtualbox settings:

* Enable Serial Port (option enabled)
* Port Mode: Host Pipe
* Connect to existing pipe/socket (option disabled)
*  Path/Address: `/tmp/vbox`

… and then `socat UNIX-CONNECT:/tmp/vbox PTY,link=/tmp/vbox` and `screen /tmp/vbox` provide a working serial environment (just `socat - UNIX-CONNECT:/tmp/vbox` doesn't seem to be 8-bit clean?).

**Comment by mika** [comment]
Also thanks to @haidinger for the detailed bug report, this clearly helped in tracking this down! :+1:

**Comment by henning-schild** [comment]
Are there netboot daily images available? I would like to deploy a fixed  version on my tftp/pxe server already, not waiting for a release.

**Comment by mika** [comment]
@henning-schild you can download daily ISOs from https://grml.org/daily/, boot it inside a VM or so, and then run:

```
ln -s /usr/lib/PXELINUX/pxelinux.0 /usr/lib/syslinux/
/usr/share/grml-live/scripts/generate_netboot_pacakge.sh / netboot.tar.xz
```

This should give you the relevant files.

**Comment by henning-schild** [comment]
@mika i tried that a couple of days ago but was stuck with that new systemd question about locales, i tried again today and can not get NFS to work

It comes up complaining about the kernel not supporting NFSv3 and all tries to convince it to use v4 seem to fail. The server supports both i tested that. Is that netboot nfs setup regularly tested and maybe there are scripts and setup bits to copy?

**Comment by mika** [comment]
@henning-schild I'm afraid you ran into this bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1022172 (thanks to @akorn for spotting)

**Comment by akorn** [comment]
@henning-schild as a workaround, you can remaster grml and force inclusion of the sunrpc module in the initramfs; that should help re-enable nfs booting.

I have the following in a `/etc/grml/fai/config/files/etc/initramfs-tools/modules/SOME-FAI-CLASS` file:

```
sunrpc
nfs
lockd
grace
nfs_acl
nfsv3
auth_rpcgss
rpcsec_gss_krb5
rpcrdma
```
While this is probably not minimal, it should cause nfsroot to work.

You also need a script in `/etc/grml/fai/config/scripts/SOME-FAI-CLASS/` that includes the line `fcopy -v /etc/initramfs-tools/modules`, and add the `SOME-FAI-CLASS` class when building your iso.

**Comment by haidinger** [comment]
Good news: Tested this vs. current prerelease grml64-2022.11-rc1 by appending "console=tty0 console=ttyS0 ssh=grml" to the default boot options: Both console and serial works and ssh is started as well! :-)

**Comment by mika** [comment]
That's great to hear, thanks for testing and reporting back, @haidinger, appreciated! :partying_face:

**Comment by henning-schild** [comment]
I just placed 2022.11 in my PXE setup. With "ssh=grml" and "console=ttyS0,115200n8"

here is the full cmdline for those who care

```
BOOT_IMAGE=grml/grml_netboot_package_grml64-full_2022.11/tftpboot/vmlinuz initrd=grml/grml_netboot_package_grml64-full_2022.11/tftpboot/initrd.img console=tty0 console=ttyS0,115200n8 root=/dev/nfs rw ip=dhcp nfsroot=/srv/nfs/grml/grml64-full_2022.11/image live-media-path=/live/grml64-full/ boot=live noeject noprompt apm=power-off ssh=grml
```

again `grml-autoconfig.service` failed

```
root@grml ~ # journalctl -u grml-autoconfig.service
Feb 01 20:38:33 grml systemd[1]: Starting Grml boot option support...
Feb 01 20:38:33 grml systemd[746]: grml-autoconfig.service: Failed to set up standard output: Input/output error
Feb 01 20:38:33 grml systemd[746]: grml-autoconfig.service: Failed at step STDOUT spawning /etc/init.d/grml-autoconfig: Input/output error
Feb 01 20:38:33 grml systemd[1]: grml-autoconfig.service: Main process exited, code=exited, status=209/STDOUT
Feb 01 20:38:33 grml systemd[1]: grml-autoconfig.service: Failed with result 'exit-code'.
Feb 01 20:38:33 grml systemd[1]: Failed to start Grml boot option support.
Feb 01 20:48:28 grml systemd[1]: Starting Grml boot option support...
Feb 01 20:48:28 grml systemd[1898]: grml-autoconfig.service: Failed to set up standard output: Input/output error
Feb 01 20:48:28 grml systemd[1898]: grml-autoconfig.service: Failed at step STDOUT spawning /etc/init.d/grml-autoconfig: Input/output error
Feb 01 20:48:28 grml systemd[1]: grml-autoconfig.service: Main process exited, code=exited, status=209/STDOUT
Feb 01 20:48:28 grml systemd[1]: grml-autoconfig.service: Failed with result 'exit-code'.
Feb 01 20:48:28 grml systemd[1]: Failed to start Grml boot option support.
```

and i only managed to get in with

```
passwd
```
set to "grml"

```
systemctl start ssh
```

i was hoping for `ssh=grml` to do both for me

the whole "user story" would be that i want a lab network where i can connect any machine and PXE boot it, and i will get "grml" with serial console working and "ssh" working

**Comment by mika** [comment]
@henning-schild hm that's annoying :disappointed: 

The:

```
Feb 01 20:48:28 grml systemd[1898]: grml-autoconfig.service: Failed to set up standard output: Input/output error
Feb 01 20:48:28 grml systemd[1898]: grml-autoconfig.service: Failed at step STDOUT spawning /etc/init.d/grml-autoconfig: Input/output error
```

looks strange to me, is that really only failing due to the `ssh=grml` boot option and working otherwise? :thinking:

**Comment by henning-schild** [comment]
> @henning-schild hm that's annoying disappointed
> 
> The:
> 
> ```
> Feb 01 20:48:28 grml systemd[1898]: grml-autoconfig.service: Failed to set up standard output: Input/output error
> Feb 01 20:48:28 grml systemd[1898]: grml-autoconfig.service: Failed at step STDOUT spawning /etc/init.d/grml-autoconfig: Input/output error
> ```
> 
> looks strange to me, is that really only failing due to the `ssh=grml` boot option and working otherwise? thinking

i can not tell right now, i hope i gave you everything i did to maybe repro ... in reality the `ssh=grml` was `ssh=a` but that hopefully is not the reason why it does not work as i expected it to

**Comment by haidinger** [comment]
@henning-schild: have you tried if your PXE boot works in other options configurations? That is, without serial console and ssh, serial only or ssh only? Just to verify if either console or ssh boot options are really the culprit.

**Comment by henning-schild** [comment]
I will have another look and pull it out as its own issue if needed, so we can finally stop discussion in a long closed issue.
