### ISSUE TITLE
Grml 2021.07 [full x2] has troubles booting usb

### ISSUE THREAD

**Issue by sixcentgeorge** [grml/grml#177]
i used latest ultraiso [ that was updated recently ] ; pen drive linux and rufus...
by now only the stick made by rufus was able to launch correctly the syslinux menu of boot...with an old pc : having the intel chipset 5520 [ dual cpu ] ichr10...
i tried to boot the same stick with an aorus pro with and amd ryzen 3700 and 64 Go of ram .. but no way... even if i do it from bios that find a second part uefi...

the amd gigabyte board is also very "dumb" and unable to install win7.. and i have it very hard with 10 or 11... [ the one that works in all case is a mix based on 11 with a tpm ...bypass.. UEFI IS SHIT ]
linux mint is not having troubles.. but i will recheck now that i have few stick "ready loading linuxes]

**Comment by sixcentgeorge** [comment]
i tested linux mint boot : it uses grub..

**Comment by sixcentgeorge** [comment]
i had a look at the page about the distro..and you seem both using the latest grub...
but the one coming with grml is quite diferent from the one Mint uses..
the boot and below folder indicates that grml seems using the latest grub...
the folder : EFI\BOOT
does the same.. but the file in the mint cdrom are having the digital signature from M$ for 
BOOTx64.EFI ..  grubx64.EFI  from Canonical Ltd. Secure Boot Signing (2017) and a mmx64.EFI by shim ... i want to try some "manual update" after i ll found the 2.06 grub package...

**Comment by mika** [comment]
If you have Secure Boot enabled on your system, then the Grml ISOs won't boot. Once you disable Secure Boot, then it should work just fine, otherwise (if you need Secure Boot) you have to build a Grml ISO with Secure Boot support enabled.

**Comment by sixcentgeorge** [comment]
my goal is to build a new remastered iso.. for playing a game like counter-strike source loaded in ram...
how i can enable the secure boot support... is it possible to enable "nvidia-ati" proprietary driver support at boot ?
i mean by adding the archive of drivers in a folder and then at boot : with a special setting ; grml extract and load the right driver..
that could be great in case of using a 3D software or keep at the console to decide to load or not .
my latest pc has 64 Go of ram and a rx 480 + a 1060 gt ...  so i shoult test all cases with the help of few old computers.. [ only the latest is uefi ..and secure boot is a terrible mess...even with windows install ...  [ may be because of some intel hardware code for uefi... ]  i am very happy with my old mainboard and cpu having 10 years or more...[ i found few mobo years ago with  1366 lga ] [hp touchsmart 600 -11*0] are also very good ...after 10 years i have two of them still working with only one mainboard dead..and replaced by ebay... 8 Go +i7 .. and few vga..later that is still "new"... [ or so..] i would love to "sabertooth them" i mean upgrading the little components of the mainboards...by some "rock solid" i ll need a D2R2 at home l;"]

**Comment by mika** [comment]
Sorry @sixcentgeorge, but your message is quite hard to read and understand for me. :-/

We don't support the proprietary nvidia-ati driver nor counter-strike or so. If you want to build/remaster Grml ISOs, take a look at our build tool grml-live, see https://grml.org/grml-live/ + https://github.com/grml/grml-live.

If you should have any concrete issues feel free to report them, though please start with reading available documentation and follow our issue templates and be more specific in your bug reports, also see https://grml.org/bugs/ and https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by sixcentgeorge** [comment]
you should remember ..i made during months a "grml4d" iso ..that was a remastered grml made to launch the server with all files in ram...that was possible with 8 Go of ram or so..  by now 64 or 256 Go are quite possible for pc user ..so i try to do a grml4d for the players.. for them to have best ping and so...
so launching driver some drivers was something i think was easy.. because the now difference between grml-full and small : is the use of "proprietary files" like drivers.. [?]
WITH MY VERY OLD PC like the touchscreen hp 600-1160 ..i tried the "mint /ubuntu" nvidia driver but it is too old [ g 210..]
so i use the free driver..  installing driver can break a good install "in all others parts" what is why i liked the idea of installing it at boot .. and with a launch parameter..[ in case of updates]


by the way i checked to use the mint folder with the signed files instead of the current one,[ in root usb/cdrom /EFI /BOOT ] , [ with the efi pc.. ]
https://www.gigabyte.com/fr/Motherboard/X570-AORUS-PRO-rev-11-12#kf

the grub menu is showing....
when i try to launch grml ..the pc crashes with a warning about signature of vmlinuz missing...
so that seems a good door to use mint and try to get some info from them for "passing" the efi  boot

**Comment by sixcentgeorge** [comment]
i made several screen captures ...
they are stored in the gallery : https://postimg.cc/gallery/4YwkvyZ

https://i.postimg.cc/Njt7tvZt/IMGA0018-FILEminimizer.jpg
https://i.postimg.cc/L8Vk60M1/IMGA0021-FILEminimizer.jpg
 show the bios menu.. the philips usb stick is having mint distro and the other kingston : grml64 full 07-2021
in the part where you can overide boot..  may be i can disable the secure boot.. [ i did too many setting tests with win7 to check that point.. plus win11 beta i was lucky to install is not this bad.. ] the effect of compiling for better cpu has its good sides..
but that is still some M$ product with the "taskmanager impossible to launch..so it is impossble to optimise a windows...or you have to cut it in half or quarters... [ like the ms windows facing google android...] it is also impossible to use winx64 softwares because some dll links are missing in the new one....of win11...[that will not cause troubles.. it is only "hardware dlls.."

the last image shows the message  :  
https://i.postimg.cc/QC51LfbV/IMGA0028-FILEminimizer.jpg
that boot/grml64full/vmlinuz has invalid signature
then loading initrd
followed by error : you need to load kernel first...

then : press a key and return to menu...

**Comment by sixcentgeorge** [comment]
what about the secure boot compilation parameters ?

**Comment by mika** [comment]
You need to build your ISO using grml-live with `SECURE_BOOT=debian` enabled.

**Comment by sixcentgeorge** [comment]
why you do not add a download ..or torrents or both links for getting grml-small-full secures ...???

plus a big thanks to me grml4d / sixcentgeorge for the old and new bugs i have found ;'] that will be good to me...i plan to write to steam for a job.. they have abandonned their steamos... so i am trying to mix both products in one... and some cool words from you can help..  

may be you are good at hlsdk ? i need some dlls for a giant mod [ made mainly with a lot of maps made for mods ]  i need them for the "monsters..." of course.. but most devs [even from valve or gearbox or the market.. are too much "far away from this old engine .." made with visual studio 6

**Comment by sixcentgeorge** [comment]
any news ??  why closing so fast ?
