### ISSUE TITLE
"Load to RAM" not working with grml64-full 2021-07

### ISSUE THREAD

**Issue by csarn** [grml/grml#179]
**Describe the bug**
When I boot the grml64-full 2021-07 iso image with legacy BIOS (i.e. via qemu), so that it runs ISOLINUX boot manager,
and in the menu I select "Boot options for grml64-full" -> "grml64-full - Load to RAM",

I get the error message:
```
(...)
Begin: Running /scripts/init-bottom ... done.
run-init: can't execute '/sbin/init': No such file or directory
```

**Steps To Reproduce**
```
 > qemu-system-x86_64 -boot d -cdrom grml64-full_2021.07.iso
```
and select the menu entry described above.

**Expected behavior**
It should copy the squashfs image to ram and continue booting like earlier versions of grml.

**In which Grml Version did the bug occur?**
grml64-full 2021-07

Output of `grml-version`:
```sh
# grml-version
grml64-full 2021.07 Release Codename JauKerl [2021-07-25]
```

**Additional context**
To narrow down the reason, it seems that grml-live build does not successfully configure the isolinux configuration file.
The boot command line for the "Load to RAM" option contains:
```
toram=%SQUASHFS_NAME%
```
which should have been replaced to 
```
toram=grml64-full.squashfs
```
When fixing that on the isolinux command line, it loads to RAM successfully.

**Comment by mika** [comment]
Thanks for reporting this in such detailed and reproducible steps, @csarn!
(Sorry, I used the "wrong chris" inside the commit message credits, will fix this for the changelog!)

FTR, ISOs in EFI boot (so therefore using GRUB instead of isolinux/syslinux) are *not* affected.

**Comment by csarn** [comment]
Thanks for the quick fix!
