### ISSUE TITLE
f2fs support

### ISSUE THREAD

**Issue by arun54321** [grml/grml#180]
Please add support for mounting and fsck for f2fs.

**Comment by mika** [comment]
I suppose it would be enough to ship `f2fs-tools`?

**Comment by arun54321** [comment]
f2fs kernel module and f2fs-tools are enough.

**Comment by mika** [comment]
Then the upcoming stable release will include support for it :) Also the daily ISOs (https://daily.grml.org/) are supposed to include those as of tomorrow (2021-10-06).
Thanks for your suggestion!
