### ISSUE TITLE
Certificate expired on https://git.grml.org/

### ISSUE THREAD

**Issue by Onfroygmx** [grml/grml#181]
Hello,

The certificate seems to have expired on 05/10 on your git website.
![image](https://user-images.githubusercontent.com/25054585/136049395-68b79c90-de0d-436e-bb76-920b21b43e9d.png)

Regards,

Onf

**Comment by mika** [comment]
Ouch, thanks for bringing this to our attention. Fixed the SSL certificate situation and added the system to monitoring, so we hopefully catch this upfront if this should ever happen again. :)

**Comment by Onfroygmx** [comment]
No problem, picked it up easily in a script using:
curl -fsSL -o /mnt/root/.zshrc  https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
Can confirm that it works now.
Onf
