### ISSUE TITLE
2021.7 and nightly ISB images both unbootable on Dell XPS 15 9550

### ISSUE THREAD

**Issue by tim-seoss** [grml/grml#188]
**Describe the bug**
2021.7 and nightly both unbootable on Dell XPS 15 9550.

**Steps To Reproduce**
UEFI and Legacy boot both fail for USB sticks written with nightly and 2021.7 grml images.

Secure boot is disabled, and 'usb' is chosen in the one-time boot menu 'F12' - there are no other menu items, and all firmware setup options have been tried.  No apparent problems installing / booting Debian, or booting other OS from USB (using same USB device and port).

No GRML menu is displayed, and the firmware displays "Boot failed" message (with subsequent prompt to retry / enter setup etc.).

From `getSystemId` under Debian:

```
Libsmbios version:      2.4.3
Product Name:           XPS 15 9550
Vendor:                 Dell Inc.
BIOS Version:           1.14.0
```

**Comment by mika** [comment]
@tim-seoss that's an interesting one.
Just to clarify: you created the USB stick with `dd if=grml64….iso of=/dev/sdX`, using a grml64 flavor?
If so, does booting the Grml ISO work through [Ventoy](https://ventoy.net/en/index.html)?

**Comment by tim-seoss** [comment]
Sorry, this was my mistake - my excuse it some weird system firmware behaviour - it still presented a boot option for a disabled device, but then failed to boot from it, I must have changed the setting in question (which is not grouped with the other boot options in the firmware setup), between testing the Debian installer usb boot, and the grml one.

Sorry for the noise!

**Comment by mika** [comment]
@tim-seoss no worries, thanks for the feedbach :)
