### ISSUE TITLE
Chroot cannot find /bin/zsh

### ISSUE THREAD

**Issue by zounp** [grml/grml#189]
**Describe the bug**
Chroot cannot find /bin/zsh

**Steps To Reproduce**
# mount /dev/sda1 /mnt
# for i in /dev /dev/pts /proc /sys /run; do mount --bind $i /mnt/$i; done
# chroot /mnt
chroot: failed to run command `/bin/zsh`: No such file or directory 

**Expected behavior**
chroot should not yield an error message but find /bin/zsh
Doing the same with a Parted Magic disk works as expected: No error message.

**In which Grml Version did the bug occur?**
grml64-full 2021.07

**Comment by mika** [comment]
@zounp the `$SHELL` environment variable on Grml points to `/bin/zsh` by default, if you want to chroot into a system which doesn't provide `/bin/zsh`, you either need to set the variable accordingly, or just invoke `chroot` command with the binary you want to invoke, like:

```
chroot /mnt /bin/bash
````

BTW: you might like to look into usage of `grml-chroot`, where all you need to do is then run:

```
mount /dev/sda1 /mnt
grml-chroot /mnt /bin/bash
```

**Comment by zounp** [comment]
Indeed. Did not think of zsh not being pressent on the computer. Sorry for the inconvenience. Thanks for the explantion.
Thanks for pointing to grml-chroot.
