### ISSUE TITLE
grml-quickconfig / run-welcome script not running at the very end of boot process

### ISSUE THREAD

**Issue by mika** [grml/grml#19]
Should run at the very end, but on real™ hardware it's running somewhere in the middle instead (seems to be fine and non-reproducible in VMs):

![grml-quickconfig](https://cloud.githubusercontent.com/assets/115592/25753434/befb40ca-31bb-11e7-9af5-90c8323b3082.jpg)

**Comment by mika** [comment]
Actually it seems to be fine only in VirtualBox, the problem can be easily reproduced by booting via KVM.

**Comment by xtaran** [comment]
Didn't show up on a Thinkpad T470s (amd64, fast, USB3) for me, but showed up on an EeePC 900A (i386, rather slow, no USB3).
