### ISSUE TITLE
LVM uses read-only kernel command line flag directly

### ISSUE THREAD

**Issue by madduck** [grml/grml#190]
**Describe the bug**
When `read-only` is passed at boot, and the block devices later turned read-write, LVM doesn't care and enforces read-only for all the LVs it handles.

**Steps To Reproduce**
1. Boot `grml` with `read-only` boot flag
2. Use `blockdev --setrw` on block device to make it read-write
3. Create GPT, PV, VG
4. Observe LVM failing to create an LV:

```
root@grml ~ # lvcreate -n root -L 24G emerald-vg
  Failed to initialize logical volume emerald-vg/root at position 0 and size 4096.
  Aborting. Failed to wipe start of new LV.
```

Also, in this mode, existing LVs cannot actually ever be written, even if the underlying block device has been set to read-write:

```
root@grml ~ # lvs /dev/emerald-vg/root       
  LV   VG         Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  root emerald-vg -Ri-a----- 23.28g                                                    
root@grml ~ # mount /dev/emerald-vg/root /mnt
mount: /mnt: WARNING: source write-protected, mounted read-only.
```

Here is the PV:

```
  PV         VG         Fmt  Attr PSize   PFree
  /dev/sda3  emerald-vg lvm2 a--  148.07g    0 
```

and the VG — note the `w` flag that indicates writeable:

```
root@grml ~ # vgs
  VG         #PV #LV #SN Attr   VSize   VFree
  emerald-vg   1   5   0 wz--n- 148.07g    0 
```

Before activation, the LV looks all good, and also has the `w` flag:

```
root@grml ~ # lvs /dev/emerald-vg/root
  LV   VG         Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  root emerald-vg -wi------- 23.28g
```

But then I activate the VG, and things change, without an error message anywhere:

```
root@grml ~ # vgchange -ay            
  5 logical volume(s) in volume group "emerald-vg" now active
root@grml ~ # lvs /dev/emerald-vg/root
  LV   VG         Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  root emerald-vg -Ri-a----- 23.28g
```

Note the `R` flag!

What's extra weird is that LVM itself seems to think the volume is writeable:

```
root@grml ~ # lvchange -p rw /dev/emerald-vg/root
  Logical volume emerald-vg/root is already writable.  Refreshing kernel state.
  Logical volume emerald-vg/root changed.
root@grml ~ # lvs /dev/emerald-vg/root
  LV   VG         Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  root emerald-vg -Ri-a----- 23.28g                  
```

**Expected behavior**
LVM should work off the actual device status, and not somehow access the kernel command-line directly. That is, once I made the devices read-write, it should just work as always.

**In which Grml Version did the bug occur?**

grml64-full 2021.07 Release Codename JauKerl [2021-07-25]

**Comment by mika** [comment]
@madduck interesting find! Did you verify whether the problem exists only due to the `read-only` option in the kernel command line? As in: boot in normal Grml mode, then run `blockdev --setro /dev/...` for all present devices, then `blockdev --setrw ...` for the actual device and then reproduce the steps mentioned above?

**Comment by madduck** [comment]
No, I did not verify this, as I had already spent way too much time on this laptop, and I handed it off to the owner as soon as I finally fixed it.

I'll try to do this at some point during the week. No promises though, so if anyone else feels inclined…

**Comment by madduck** [comment]
I think I found the issue. LVM is not at fault at all. Rather, `/etc/udev/scripts/forensic-mark-readonly` will mark all new block devices r/o when the keyword is present on the kernel command line.

So the LV was assembled alright, but then udev actually made it read-only. And indeed, this then makes it r/w: `blockdev --setrw /dev/emerald-vg/root`.

Sorry for the noise.

**Comment by mika** [comment]
@madduck glad you managed to solve it yourself, thanks for your feedback! :+1:
