### ISSUE TITLE
grml64-2022.11-rc1: sysctl errors during boot shown on serial console: unrecognized option '--pattern'

### ISSUE THREAD

**Issue by haidinger** [grml/grml#193]
**Describe the bug**
When verifying issue #176 (https://github.com/grml/grml/issues/176), I noticed sysctl errors in the serial console.

**Steps To Reproduce**
Boot grml64-2022.11-rc1 ISO with serial console enabled (did this in Virtualbox, see #176) 

Capture of the serial output:
...
[    4.871038] Run /init as init process
Loading, please wait...

Welcome to

   ____              _
  / ___| _ __ _____ | |
 | |  _ | / /|     || |
 | |_| ||  / | | | || |
  \____||_|  |_|_|_||_|

Grml Live Linux - http://grml.org/

 * Running grml64-full 2022.11-rc1 Release Codename MalGuckes [2022-11-11]
 * Finished early booting sequence. [ ok ]
 * Searching for GRML file, this might take a few seconds...
Starting systemd-udevd version 252.1-1
Begin: Loading essential drivers ... /sbin/sysctl: unrecognized option '--pattern'
BusyBox v1.35.0 (Debian 1:1.35.0-4) multi-call binary.

Usage: sysctl [-enq] { -a | -p [FILE]... | [-w] [KEY[=VALUE]]... }

Show/set kernel parameters

        -e      Don't warn about unknown keys
        -n      Don't show key names
        -q      Quiet
        -a      Show all values
        -p      Set values from FILEs (default /etc/sysctl.conf)
        -w      Set values
/sbin/sysctl: unrecognized option '--pattern'
BusyBox v1.35.0 (Debian 1:1.35.0-4) multi-call binary.

Usage: sysctl [-enq] { -a | -p [FILE]... | [-w] [KEY[=VALUE]]... }

Show/set kernel parameters

        -e      Don't warn about unknown keys
        -n      Don't show key names
        -q      Quiet
        -a      Show all values
        -p      Set values from FILEs (default /etc/sysctl.conf)
        -w      Set values
/sbin/sysctl: unrecognized option '--pattern'
BusyBox v1.35.0 (Debian 1:1.35.0-4) multi-call binary.

Usage: sysctl [-enq] { -a | -p [FILE]... | [-w] [KEY[=VALUE]]... }

Show/set kernel parameters

        -e      Don't warn about unknown keys
        -n      Don't show key names
        -q      Quiet
        -a      Show all values
        -p      Set values from FILEs (default /etc/sysctl.conf)
        -w      Set values
/sbin/sysctl: unrecognized option '--pattern'
BusyBox v1.35.0 (Debian 1:1.35.0-4) multi-call binary.

Usage: sysctl [-enq] { -a | -p [FILE]... | [-w] [KEY[=VALUE]]... }

Show/set kernel parameters

        -e      Don't warn about unknown keys
        -n      Don't show key names
        -q      Quiet
        -a      Show all values
        -p      Set values from FILEs (default /etc/sysctl.conf)
        -w      Set values
done.
Begin: Running /scripts/init-premount ... done.
Begin: Mounting root file system ... Begin: Running /scripts/live-top ... done.
...

**Comment by mika** [comment]
Thanks, that's something we should look into then! :)

**Comment by mika** [comment]
So this is another regression from nfs-kernel-server (1:2.6.2-1) (source package nfs-utils) with its `/usr/lib/modprobe.d/50-nfs.conf`( similar to https://github.com/grml/grml/issues/192 - Cc @akorn):

```
# cat /usr/lib/modprobe.d/50-nfs.conf         
# Ensure all NFS systctl settings get applied when modules load

# sunrpc module supports "sunrpc.*" sysctls
install sunrpc /sbin/modprobe --ignore-install sunrpc $CMDLINE_OPTS && { /sbin/sysctl -q --pattern sunrpc --system; exit 0; }

# rpcrdma module supports sunrpc.svc_rdma.*
install rpcrdma /sbin/modprobe --ignore-install rpcrdma $CMDLINE_OPTS && { /sbin/sysctl -q --pattern sunrpc.svc_rdma --system; exit 0; }

# lockd module supports "fs.nfs.nlm*" and "fs.nfs.nsm*" sysctls
install lockd /sbin/modprobe --ignore-install lockd $CMDLINE_OPTS && { /sbin/sysctl -q --pattern fs.nfs.n[sl]m --system; exit 0; }

# nfsv4 module supports "fs.nfs.*" sysctls (nfs_callback_tcpport and idmap_cache_timeout)
install nfsv4 /sbin/modprobe --ignore-install nfsv4 $CMDLINE_OPTS && { /sbin/sysctl -q --pattern 'fs.nfs.(nfs_callback_tcpport|idmap_cache_timeout)' --system; exit 0; }

# nfs module supports "fs.nfs.*" sysctls
install nfs /sbin/modprobe --ignore-install nfs $CMDLINE_OPTS && { /sbin/sysctl -q --pattern fs.nfs --system; exit 0; }
```

**Comment by mika** [comment]
This is fixed with latest grml-live release and upcoming daily ISOs will also include this bug fix.
Salvatore Bonaccorso also takes care of another approach with linux-nfs upstream as part of https://bugs.debian.org/1022172

**Comment by mika** [comment]
Thanks @haidinger for the detailled bug report, thanks @akorn for great debugging and valuable feedback!
