### ISSUE TITLE
grml64-small_2022.11-rc1: iptables is missing for grml-router

### ISSUE THREAD

**Issue by jkirk** [grml/grml#196]
**Describe the bug**
`iptables` is missing for `grml-router`

**Steps To Reproduce**
```
  grml@grml ~ % sudo grml-router
  iptables: binary not found
```

**In which Grml Version did the bug occur?**

Output of `grml-version`:
```sh
  grml@grml ~ % grml-version
  grml64-small 2022.11-rc1 Release Codename MalGuckes [2022-11-11]
```

Please add `iptables`.

**Comment by mika** [comment]
Thanks, didn't have that in mind anymore! Fixed via grml-network package
