### ISSUE TITLE
Can't boot Grml in a VirtualBox with 512 MB RAM

### ISSUE THREAD

**Issue by cyberchrime** [grml/grml#197]
**Describe the bug**
When trying to boot _grml64-full_2022.11.iso_ in a VirtualBox with only 512 MB RAM, the Linux Kernel can not find _init_. See the following screenshot. However, after increasing RAM to 1 GB, everything works fine.

**Steps To Reproduce**
Install VirtualBox, select _New_ and create a new 64-Bit Linux VirtualBox (no creation of a virtual hard disk required). Select to use 512 MB RAM (if it does not appear immediately, enable Expert Mode). Afterwards, attach the image _grml64-full_2022.11.iso_ and boot from it.

**Expected behavior**
As stated in [the Grml requirements](https://grml.org/faq/#requirements), it should boot fine with only 512 MB RAM.

**Screenshot**
![VirtualBox_grml_03_12_2022_13_27_35](https://user-images.githubusercontent.com/20052188/205441279-37b73103-5464-48db-8dc7-92acffbb0936.png)

**In which Grml Version did the bug occur?**
_grml64-full_2022.11.iso_

**Comment by mika** [comment]
Ah good find, thanks for reporting! I'll update the FAQ accordingly :)
