### ISSUE TITLE
grml 2022.11 does not boot from image placed on LVM logical volume

### ISSUE THREAD

**Issue by michaellass** [grml/grml#200]
**Describe the bug**
I am using grml-rescueboot to include grml as a boot option in my GRUB loader. The grml image is placed inside an LVM logical volume. This worked perfectly with grml 2021.07 and earlier but does not anymore with grml 2022.11 and current daily builds.

The boot fails after unsuccessfully waiting for the device to show up. Screenshots follow below.

**Steps To Reproduce**
```
 > Create LVM logical volume, format as ext4, mount under /boot/grml
 > Place image of grml-full 2022.11 inside that folder
 > Install grml-rescueboot
 > Regenerate grub config
 > Try to boot into the grml GRUB entry
```

**Expected behavior**
grml should boot correctly, as it did with grml 2021.07.

**Screenshots**
Trying to boot grml in debug mode shows the following output repeating several times before the boot is declared as failed and one is dropped into the initramfs shell:

![signal-2023-01-06-195549_002](https://user-images.githubusercontent.com/11042539/211081866-105f1f9e-748e-4cc0-a180-d65b3b93ee85.jpeg)

The error shown after those unsuccessful attempts:

![signal-2023-01-06-195432_002](https://user-images.githubusercontent.com/11042539/211081820-c9d82e99-d629-4e34-97f2-d85fcbf096d1.jpeg)

**In which Grml Version did the bug occur?**
I tested with the following images on two different systems:
* grml64-full_2022.11.iso
* grml32-full_2022.11.iso
* grml64-full_sid_build4024.iso
* grml64-full_testing_build4118.iso

**Additional context**
After being dropped into the initramfs shell, I tried to access the volume. It is listed by `lvm lvs` but not as active. It can be activated using `lvm lvchange -a y linux/images` and is then available at /dev/linux/images as well as /dev/mapper/linux-images:

![signal-2023-01-06-195336_002](https://user-images.githubusercontent.com/11042539/211081752-c464dbb6-1dcf-4866-862e-08af55e61763.jpeg)

So maybe the bootup procedure is just missing an activation of those logical volumes?

**Comment by mika** [comment]
Hm yeah, that sounds like something in the lvm2 hook, live-boot (live-boot-grml-initramfs-tools) or initramfs-tools seems to be missing/broken. :( Thanks for the detailed bug report! :+1:

**Comment by michaellass** [comment]
I spent some time to figure out what has changed and I have a strong suspicion that it is this change in Debian's lvm2 package: https://salsa.debian.org/lvm-team/lvm2/-/commit/2340adad4b3875331be1ba7abba881cc1b6e6738

The first package version with that change is 2.03.15-1 and in fact this is included in grml 2022.10 but not in 2021.07:
* https://grml.org/files/grml64-full_2022.11/dpkg.list
* https://grml.org/files/grml64-full_2021.07/dpkg.list

The change removes a script from the initramfs that previously activated the logical volume. Now it is expected to be activated via a udev rule.

If I understand those files correctly, the initramfs script only activated the LVs that hold the root volume and the resume volume. The udev rule looks like it just activates all available and complete VGs.

Related issues/discussions:
* https://github.com/grml/grml/issues/110
* https://github.com/grml/grml/issues/31

So I understand that `69-lvm-metad.rules` is removed on purpose but I guess we need either that or need to revive the initramfs script to fix this issue.

**Comment by mika** [comment]
@michaellass wow, _thanks_ for looking  further into this! Nice finding! :+1: 

I'm afraid of unexpected behaviors if we just (re-)enable `69-lvm-metad.rules` by default, though if we manage to run this udev file only when booted via grml-rescueboot/findiso AKA `loopback` mode (that would be something like `findiso=...` being set to something other than empty `findiso=` IIRC), that might be worth a try?

**Comment by michaellass** [comment]
That would be an option, although I am not sure how to realize that. Maybe with an environment variable that is set or by a little script that is run by udev to evaluate the rule. However, with that solution still all VGs and LVs would be activated when booting via grml-rescueboot (even when not booting from LVM).

I wonder if it would be possible to activate the volume based on the `live-media` or `bootfrom` kernel args. They are set by grml-rescueboot and contain the logical volume, so it would be possible to activate just that:
https://github.com/grml/grml-rescueboot/blob/8c499f10caf12cba536520dd4f1f765cb4f1251f/42_grml#L109

For example, in my case this is set to `live-media=/dev/nvme0n1p5,/dev/mapper/linux-images`.

Maybe it could be done here? https://github.com/grml/live-initramfs-grml/blob/2c25930c4b6e12496163b6b3f0c666a1121363e9/scripts/live#L214

**Comment by michaellass** [comment]
I was thinking about something similar to the original initramfs script:

```bash
lvchange_activate() {
	lvm lvchange -aay -y --sysinit --ignoreskippedcluster "$@"
}

IFS=,
for dev in $(echo "$LIVE_MEDIA"); do
	case "$dev" in
	/dev/mapper/*)
		eval $(dmsetup splitname --nameprefixes --noheadings --rows "${dev#/dev/mapper/}")
		if [ "$DM_VG_NAME" ] && [ "$DM_LV_NAME" ]; then
			lvchange_activate "$DM_VG_NAME/$DM_LV_NAME"
		fi
		;;
	/dev/*/*)
		# Could be /dev/VG/LV; use lvs to check
		if lvm lvs -- "$dev" >/dev/null 2>&1; then
			lvchange_activate "$dev"
		fi
		;;
	esac
done
unset IFS
```

**Comment by mika** [comment]
@michaellass oh that sounds like a _great_ and even better approach! IMO this is clearly worth a try! Could you maybe create a PR against live-boot-grml[1]? 

[1] Sorry, I noticed that we still have https://github.com/grml/live-initramfs-grml around while it was deprecated many years ago and we forgot to properly deprecate it. It's replacement is live-boot-grml (based on debian-live's project to be closer to Debian), and the corresponding line is https://github.com/grml/live-boot-grml/blob/35b6ae0bceffa786cfe375c7b84383eb74ccf91e/components/9990-cmdline-old#L116 - I'll make sure to deprecated live-initramfs-grml
