### ISSUE TITLE
Command "apropos" doesn find anything

### ISSUE THREAD

**Issue by 2f2a** [grml/grml#201]
Hi, I tested "Grml" the other day, and noticed "apropos man" return nothing.

(wut I was doing: I accidentally deleted my home-directory, was sorting backup, and one slash too much.. I had the "grml" -debian package installed, noticed another inconvenience, that Debian-Grml had mounted the corrupt disk..)

**Comment by jkirk** [comment]
Just played around a bit with `apropos` and I can say that directly after booting `apropos man` did return some content.

But after some time this happened:
```
root@grml ~ # apropos man
man: nothing appropriate.
```

Running `mandb` manually fixed that for me.
We still need to find out, why the mandb got lost.

If you can, please help us by giving us some steps to reproduce this behavior.
Also please check if `/var/cache/man/index.db` really does not exist, when `apropos` returns nothing.

**Comment by jkirk** [comment]
We just found this:
```
root@grml ~ # apropos man | wc -l
590
root@grml ~ # systemctl list-timers
NEXT                        LEFT       LAST PASSED UNIT                         ACTIVATES                     
Thu 2023-02-02 15:06:09 UTC 12min left -    -      systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service

1 timers listed.
Pass --all to see loaded but inactive timers, too.
root@grml ~ # systemctl restart systemd-tmpfiles-clean.service 
root@grml ~ # apropos man        
man: nothing appropriate.
```

@mika then found this:
```
root@grml ~ # cat /usr/lib/tmpfiles.d/man-db.conf
d /var/cache/man 0755 man man 1w
```

So, the man cache gets deleted if its older than a week when `systemd-tmpfiles-clean.timer` kicks in (15 minutes after boot).
FTR, the cache is older than a week 😉 :

```
root@grml ~ # ls -l /var/cache/man/index.db 
-rw-r--r-- 1 man man 573440 Nov 29 07:16 /var/cache/man/index.db
```

We are working on a fix. Thanks for the bug report @2f2a !
