### ISSUE TITLE
grml-live-remaster fix

### ISSUE THREAD

**Issue by alhyene** [grml/grml#202]
Change from aufs to overlayfs.

If you wish remaster your own GRML... It Could be cool...

sudo ln -s /mnt/new /remaster           # mounted on some drive.
sudo mkdir /mnt/new
or
sudo ln -s /tmp/new /remaster           # mounted on tmp if you have enourgh RAM...(speeder)
sudo mkdir /tmp/new

Then sudo grml-live-remaster grml.iso where you want.

Install what you want... etc... Then type exit... wait...

grml.iso is ready where you put in.

cp grml.iso where you want...
Do what you want with it.
;*)

PS: I use (and abuse) GRML for hacking purpose... It run live with 8GB RAM that's why I try optimize it.

**Comment by mika** [comment]
@alhyene thanks for your feedback! 

So the changes you did are:

```
diff --git remaster/grml-live-remaster remaster/grml-live-remaster
index 326a1897..5d278338 100755
--- remaster/grml-live-remaster
+++ remaster/grml-live-remaster
@@ -94,8 +94,8 @@ if [ ! -r /remaster ]; then
   exit 1
 fi
 
-mkdir -p /remaster/chroot /remaster/tmp /remaster/cdrom
-mount -t tmpfs tmpfs /remaster/tmp
+mkdir -p /remaster/chroot /remaster/tmp /remaster/cdrom /remaster/work
+
 echo "#:# edit the following two lines to change the boot message" >/remaster/msg
 echo "#:#" >>/remaster/msg
 if [ -r ${LIVE_PATH_BOOT}/isolinux/boot.msg ] ; then
@@ -107,8 +107,8 @@ if ! grep -q "/remaster/cdrom squashfs" /proc/mounts ;  then
    mount -t squashfs "$SQUASHFS_FILE" /remaster/cdrom -o ro,loop
 fi
 
-if ! grep -q "aufs /remaster/chroot" /proc/mounts ; then
-   mount -t aufs aufs /remaster/chroot -o br:/remaster/tmp=rw:/remaster/cdrom=rr
+if ! grep -q "overlay /remaster/chroot" /proc/mounts ; then
+   mount -t overlay overlay -o lowerdir=/remaster/cdrom,upperdir=/remaster/tmp,workdir=/remaster/work /remaster/chroot
 fi
 
 for i in run dev dev/pts proc root sys tmp; do
```

The switch from aufs to overlay certainly makes sense and I'm happy to take that.

The removal of:

```
mount -t tmpfs tmpfs /remaster/tmp
```

is something I'm not sure about. Why did you drop that one? :)

(Disclaimer from my side: I didn't use that script since ages, while it's certainly nice to have a working script! :))

**Comment by mika** [comment]
@alhyene  I see, thanks for your feedback! Submitted the change with credits for you :)
