### ISSUE TITLE
Please consider adding zstd to grml_small

### ISSUE THREAD

**Issue by Zugschlus** [grml/grml#204]
unmkinitramfs and lsinitramfs will give misleading error messages when listing and unpacking a zstd compressed multi-segment initramfs. This is the default of building initramfs images on Debian in these days.

**Describe the solution you'd like**
include the zstd package in the grml-full and grml-small images

**Describe alternatives you've considered**
initramfs-tools-core could be hacked to give a less misleading error message ("unable to unpack zstd compressed images without zstd"), but that would still leave the user without an unpacked or listed initramfs, reducing grml's usefulness as a rescue system.

**Disk usage of the software**
 On grml 2022-11
```shell
# apt update
# apt install --assume-no zstd
[...]
After this operation, 2078 kB of additional disk space will be used.

# apt-cache show $PACKAGE | grep Installed-Size
Installed-Size: 2078 kB
```

**The Grml version and flavour you checked that didn't have the feature you are asking for**
2022-11, daily testing, daily sid (from 2024-01-14).
Initially, I suspected that initramfs-tools was not current enough to be able to unpack segmented initramfs images. it took me an hour to find out that in fact zstd was not here.

**Comment by mika** [comment]
Thanks, sounds like a good idea, implemented in grml-live, the upcoming daily grml-small ISOs are supposed to ship it also (we already have zstd included in grml-full including the latest stable releases, FTR).
