### ISSUE TITLE
No floppy disk detected in UEFI boot

### ISSUE THREAD

**Issue by d630** [grml/grml#207]
**Describe the bug**

When setting up a VM, attaching grml64-full_2022.11.iso to it and starting it with UEFI, no floppy disk is detected in Grml. Floppy disk will be detected, if BIOS is being used instead of EFI.

**Steps To Reproduce**

- create vm
- enable EFI
- attach grml64-full_2022.11.iso
- create FAT 12 floppy image
- add a file to the floppy
- attach floppy image
- start vm
- boot grml

**Expected behavior**
`/dev/fd0` is there and accesible and can be mounted on the command line. 

I am not sure, if this is a problem of the hypervisors I have used or if this is a known EFI limitation in general or if something specific must be configured in Grml.

**In which Grml Version did the bug occur?**
https://download.grml.org/grml64-full_2022.11.iso

**Additional context**
Tested with VirtualBox 7.0 on Debian 12 and with VMWare ESXi 6.7

**Comment by d630** [comment]
Same behavior with https://download.grml.org/devel/grml64-full_2024.02-rc1.iso

**Comment by mika** [comment]
Thanks, confirmed. It looks like this legacy floppy disk drive isn't supported in EFI, https://forums.virtualbox.org/viewtopic.php?t=106134. AFAICT this is not a Grml problem, but actually a limitation of EFI/VirtualBox.

**Comment by d630** [comment]
Ok, you must be right. It's the same problem in VirtualBox and ESXi, but the floppy is detected using QEMU/KVM. I'm closing this ticket, thank you.

PS: Just for the records: https://forum.virtualbox.org/ticket/21892

**Comment by mika** [comment]
Thx! :+1:
