### ISSUE TITLE
apt fails to install nginx

### ISSUE THREAD

**Issue by KyleSebion** [grml/grml#210]
**Describe the bug**
apt fails to install nginx.

**Steps To Reproduce**
```
 > apt -y install nginx # or nginx-full
```

**Expected behavior**
Successful install. 

**Screenshots**
-  grml64-small_2024.02.iso
    - nginx-full
        - ![20240919_221453](https://github.com/user-attachments/assets/24765bda-64ad-4e88-aa43-a1e5d91f62e3)
    - nginx
        - ![20240919_221714](https://github.com/user-attachments/assets/74585d09-a5fe-405e-9b44-f5573de11e8b)
- grml64-full_2024.02.iso
    - nginx-full
        - ![20240919_222036](https://github.com/user-attachments/assets/f2f7d854-4db8-4c5d-894b-466065fde422)
    - nginx
        - ![20240919_222241](https://github.com/user-attachments/assets/0a0cd55f-d050-48f7-a088-49f6c7c04fb7)

**In which Grml Version did the bug occur?**

Output of `grml-version`:
```sh
# grml-version
grml64-full 2024.02 Release Codename Glumpad [2024-02-26]
```

**Additional context**
My workaround:
```
apt -y install nginx # fails
cp -v /etc/nginx/nginx.conf{.dpkg-new,}
cp -v /etc/nginx/mime.types{.dpkg-new,}
systemctl restart nginx
apt -y install nginx # works now
```

**Comment by mika** [comment]
Thank you for reporting this, very interesting™ behavior, I can even reproduce this with current grml64-full daily ISOs.

**Comment by mika** [comment]
This is actually a bug in the nginx packaging of Debian, reported as https://bugs.debian.org/1082373, it's not Grml specific, therefore closing it here. Thanks for reporting!
