### ISSUE TITLE
img support?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [grml/grml#212]
Hi, looks like currently it supports iso only?

**Comment by mika** [comment]
I don't understand your question, what's "img support" supposed to mean? Our ISOs are "dd-able", so you can directly write them to a USB device or alike, is that what you're looking for?

**Comment by vitaly-zdanevich** [comment]
I am about your script that builds grub for ISOs.

**Comment by vitaly-zdanevich** [comment]
Does your script handle img files? Looks like no.

**Comment by mika** [comment]
What script are you talking about?

**Comment by vitaly-zdanevich** [comment]
grml-rescueboot

**Comment by vitaly-zdanevich** [comment]
Ops, its another repo https://github.com/grml/grml-rescueboot

**Comment by mika** [comment]
Ah, now I kind of see what you're talking about :smile: 
This is continued at https://github.com/grml/grml-rescueboot/issues/20
