### ISSUE TITLE
warnings/errors on grml-small

### ISSUE THREAD

**Issue by Zugschlus** [grml/grml#24]
Hi,

grml-small emits the following error messages on boot:

[ WARN ] loadcpufreq init script not available, ignoring cpu frequency scaling.
[ FAIL ] amixer binary not available. Can not set sound volumes therefore.

This is a cosmetic issue. Could it be possible to avoid those messages?

Greetings
Marc

**Comment by mika** [comment]
We could move the FAIL to a WARN, though I'm a bit afraid of completely disabling the messages since that would mean that this difference between grml-small and grml-full is quite hidden. What do others think, @grml/team-grml-developers?

**Comment by evgeni** [comment]
s/FAIL/WARN/ is fine I'd say, but I would also not remove the message completely. Not only this would hide the difference between small and full, it would also make remastering/building own flavors more dangerous (in terms of forgetting the feature).

**Comment by Zugschlus** [comment]
In Debian, most init scripts used to handle the case of an uninstalled but unpurged packages by checking for the binary before doing anything, and silently returning 0 if the binary is not there any more (e.g. binary removed and init script as a conffile still present).

I think that grml's mechanisms should behave the same way. If loadcpufreq is not installed, nooe would expect frequency scaling to be enabeld, and if alsautils is not installed, it is clear that saved volumes are not restored.

Why would the differences between -full and -small need to be advertised this prominently? I mean, -small doesn't even have dig and host(1), which is a much greater loss from my pov than amixer.
