### ISSUE TITLE
grml96-full: addons menu lists netboot.xyz, but the required binary seems to be missing

### ISSUE THREAD

**Issue by mika** [grml/grml#25]
As noticed by @schierlm on IRC

**Comment by mika** [comment]
Hej @schierlm I can't reproduce this, please reopen this issue with more details so we can investigate. Thanks!

**Comment by schierlm** [comment]
It was not grml-small, but `grml96-full_2017.05-rc1.iso` (SHA-1 **FF902FEA4A50BEC69BFCE402BB1AF089E3F23FD0**).

`boot/isolinux/addon_27_netboot.cfg` looks like this:

```
label netboot.xyz
  menu label Run ^Netboot.xyz
  kernel /boot/addons/netboot.xyz.lkrn

  text help
                                        Start Netboot.xyz for booting
                                        over the network.
  endtext
```

But, in /boot/addons there are only these files:

```
bsd4grml/
allinone.img
balder10.imz
chain.c32
hdt.c32
ipxe.lkrn
mboot.c32
memdisk
memtest
menu.c32
pci.ids
```

Please reopen, I cannot as I am not the reporter (at least GitHub does not believe so) and not repo collaborator.
