### ISSUE TITLE
Please replace MD5 checksums with SHA256 or SHA512 for all grml .iso images

### ISSUE THREAD

**Issue by MarkRijckenberg** [grml/grml#26]
Hi,

I noticed that your team still distributes MD5 and SHA1 checksums for the .iso images for grml at – for example – the following URL:

http://ftp.fau.de/grml//devel/

May I kindly ask you to take a look at the following links?

https://en.wikipedia.org/wiki/Secure_Hash_Algorithms

https://github.com/gobolinux/LiveCD/issues/8

MD5, SHA-0 and SHA1 are all vulnerable to collision attacks.

SHA256 (or SHA512) is now the standard (for the moment).

I highly recommend dropping the use of MD5 and replacing it with only SHA256 (or SHA512).

I am simply using Qubes OS as an excellent point of reference, which uses SHA256 and SHA512.

https://www.qubes-os.org/security/verifying-signatures/

https://www.qubes-os.org/downloads/

Concerning the use of Bittorrent, could you please read this?

https://www.ghacks.net/2016/02/21/linux-mint-hacked-iso-images-compromised/

If you put the .iso image and corresponding SHA256 checksum file, signature and PGP Key in a .zip file and distribute it immediately via Bittorrent BEFORE hosting it on a website, hackers will probably not be able to compromise the integrity of the .iso image, because the SHA256 checksum in the Bittorrent file is much harder to alter than one stored on a website. Furthermore, you then have the option of comparing the SHA256 value in the .torrent file with the value on the website. This goes even further than what most  GNU/Linux distributions actually do….

“The reason is simple; popular torrents are distributed from several seeders and peers, and once they are in circulation, it is not possible to manipulate the data, say replace it with a hacked image.”

Kind regards,

Mark Rijckenberg

**Comment by mika** [comment]
We already provide GPG signatures through the asc files, though we just need to provide the according SHA256/SHA512 files which are even created automatically during release builds, just not yet included in the release process. Thanks, will take care for the stable release then.

Regarding the torrents: I don't want to create yet another archive file and don't plan to create such zip files therefore (and am still not sure what it would give us).

**Comment by mika** [comment]
I think we've provided everything what's needed with the new stable release (being the gpg signature via `.asc`, and `md5, sha1, sha256 + sha512` files next to the ISOs). If something is missing or could be further improved please let us know, thanks for reporting this!

**Comment by MarkRijckenberg** [comment]
Thanks.

I see the SHA512 checksums here:

http://gd.tuwien.ac.at/opsys/linux/grml/index.de.html

SHA512 still missing here:

https://grml.org/download/

http://linuxfreedom.com/grml/download.html
