### ISSUE TITLE
slow ssh logins due to systemd-machine-id service masking

### ISSUE THREAD

**Issue by mika** [grml/grml#27]
Trying to login via ssh on Grml 2017.05-rc1 I see the following in the logs:

```
systemd-logind.service: Start operation timed out. Terminating.
Failed to start Login Service.
systemd-logind.service: Unit entered failed state.
systemd-logind.service: Failed with result 'timeout'
systemd-logind.service: Service has no hold-off time, scheduling restart.
systemd-machine-id-commit.service: Cannot add dependency job, ignoring : Unit systemd-machine-id.commit.service is masked.
```

And ssh login is horribly slow. It seems to be related to our masking of systemd-machine-id-commit, since when i `systemctl unmask systemd-machine-id` it works just fine.

**Comment by zeha** [comment]
Maybe remove logind?

**Comment by mika** [comment]
logind is part of the systemd package, I'm afraid this can't be properly done :)
