### ISSUE TITLE
LVM devices enabled by default

### ISSUE THREAD

**Issue by mika** [grml/grml#31]
lvm's /lib/udev/rules.d/69-lvm-metad.rules nowadays automatically scans for PVs (running `lvm pvscan --cache --activate -ay ...`). So it's no longer relevant to `Start lvm2[-lvmetad`.

Question is: do we want to enable LVs by default, or should we overwrite/remove `/lib/udev/rules.d/69-lvm-metad.rules` instead?

**Comment by akorn** [comment]
I don't think grml should scan for PVs by default. This can take very long on slow (e.g. faulty) devices.

I'm not sure, but I think activating a volume group can also be potentially destructive (for example in the case of mirrored PVs).

**Comment by mika** [comment]
Thanks for the feedback.

By removing the `/lib/udev/rules.d/69-lvm-metad.rules` file automatic PV scanning shouldn't happen anymore, and the behavior seems to be consistent now with what we had in previous Grml releases. The instructions and automatic enabling when using the `lvm` boot-option was broken yet though, this is fixed by the following upcoming git commit.
