### ISSUE TITLE
Document memory requirement

### ISSUE THREAD

**Issue by thomasdstewart** [grml/grml#35]
When testing the new release candidate with qemu (http://grml.org/qemu/) I could not get it booted. It would eventually drop to a "(initramfs)" prompt after the yellow "Welcome Grml" banner (the start of the initramfs).

When running qemu without any memory options it will allocate 128M. This does not seem to be enough to boot the system. This fails to boot: "qemu-system-x86_64 -enable-kvm -cdrom /srv/store/iso/grml64-full_2017.05-rc1.iso -m 215" and this boots fine: "qemu-system-x86_64 -enable-kvm -cdrom /srv/store/iso/grml64-full_2017.05-rc1.iso -m 216", so it seems that 216M is the minimal amount needed. I also did a quick test with 2014.11 and it seems to have similar issues (224M minimum), so this is not a new issue. Some ideas:
- Update http://grml.org/qemu/ to use "-m 256" (the requirement is already mentioned in https://grml.org/faq/#toc).
- Get the initramfs script to complain if there is <=256 memory.

Kind Regards
Tom

**Comment by mika** [comment]
Thanks, @thomasdstewart!
