### ISSUE TITLE
grml-x as user grml does not work

### ISSUE THREAD

**Issue by hax404** [grml/grml#41]
When i boot grml64-full_2017.05-rc1.iso in a kvm based virtual machine and type x for starting grml-x, X does not start and give me an error. I uploaded the logfile [/home/grml/.local/share/xorg/Xorg.0.log](https://froschschenkel.hax404.de/share/13309223/Xorg.0.log).

The virtual machine is what i get when i install libvirt on debian stretch and create a normal kvm based virtual machine. Here is what lspci says:
```
00:02.0 VGA compatible controller: Red Hat, Inc. QXL paravirtual graphic card (rev 04) (prog-if 00 [VGA controller])
	Subsystem: Red Hat, Inc QEMU Virtual Machine
	Flags: fast devsel, IRQ 11
	Memory at f4000000 (32-bit, non-prefetchable) [size=64M]
	Memory at f8000000 (32-bit, non-prefetchable) [size=64M]
	Memory at fc054000 (32-bit, non-prefetchable) [size=8K]
	I/O ports at c080 [size=32]
	Expansion ROM at 000c0000 [disabled] [size=128K]
	Kernel driver in use: qxl
	Kernel modules: qxl
```

grml-x works when i start it as root. With grml64-full_2014.11.iso grml-x works as user grml too.

**Comment by jkirk** [comment]
Thanks for the report. This is the same issue as #20. Please follow up / subscribe it. Closing this issue.
