### ISSUE TITLE
grml 2017.05-rc1 is stuck on "mounting root filesystems..."

### ISSUE THREAD

**Issue by PloniAlmoni** [grml/grml#42]
I'm booting EFI on a x99 i7 5820k system, during initial boot, finding the GRML file takes a very long time, then it gets stuck with mounting root filesystems. My filesystems consist of an EFI gpt SSD disk with ext4 on the root filesystem, my hard drive, for virtual machine performance reasons, is formatted with the SGI XFS filesystem supported by the Linux kernel.

**Comment by mika** [comment]
How are you booting? Via USB? How did you install Grml to your medium, using dd/grml2usb/...? Does the verbose=1 boot option provide further information where it gets stuck? How much memory does your system have?

**Comment by PloniAlmoni** [comment]
I have 32GB of RAM, installed using dd, via USB. I'll try the verbose=1 option.

**Comment by PloniAlmoni** [comment]
When I use verbose=1, I get a lot of stuff about my CPU hanging with crash-dumps. It looks like it's doing it in the noveau driver. 

My Nvidia GPU, which I ordinarily use in PCIe VGA passthrough to a non-Linux VM on Linux (hooked up to vfio rather than active in Linux) is a GTX 1070 - this is at least partially incompatible with noveau acceleration due to Nvidia's encryption of drivers (remember Linus Torvalds dropping the F-bomb on Nvidia? That was due to this!), though perhaps some progress has been made on that front that I'm unaware of. I also am using an AMD r9 390X, compatible with either radeon or amdgpu drivers (the latter is preferable.), this is what grml is displaying on, at least, on the main monitor input. Do you think this might be it?

**Comment by mika** [comment]
According to information from IRC booting with "blacklist=noveau" helped to get a working shell prompt, though raising several `NMI watchdog BUG cpu #1 stopped for 23s!` messages during boot.

**Comment by mika** [comment]
@PloniAlmoni - with `blacklist=noveau` it works in a reasonable way is Grml not usable at all then?

**Comment by PloniAlmoni** [comment]
It works reasonably then....

**Comment by mika** [comment]
Considering this issue as resolved, closing therefore.
