### ISSUE TITLE
tmux.conf on 2017.05-rc1 needs updating

### ISSUE THREAD

**Issue by winny-** [grml/grml#46]
I noticed the following warning on startup:

```
/etc/tmux.conf:48: unknown option: status-utf8
```

It appears this option is no longer needed. https://github.com/tmux/tmux/issues/230

**Comment by mika** [comment]
Thanks for the report, this is already fixed via https://github.com/grml/grml-etc-core/commit/46d7290f3992b41794767a692f7c687987256612
