### ISSUE TITLE
Please add lm-sensors

### ISSUE THREAD

**Issue by gsutre** [grml/grml#48]
Hi,

I couldn't find a way to see my system's temperatures (CPU, motherboard) with Grml 2017.05 (64-bit, full). Usually, I use the command sensors (from package lm-sensors) to do so, but this package is not build into Grml. Could you please add it?

Best regards,

Grégoire

**Comment by mika** [comment]
Thanks for the suggestion, I've just pushed the relevant change so starting with the daily.grml.org ISOs by tomorrow the grml-full ISOs will include the lm-sensors package.
