### ISSUE TITLE
please consider including dig, host, dnstools in grml-small

### ISSUE THREAD

**Issue by Zugschlus** [grml/grml#56]
Hi,
I'd like to be able to do some DNS resolving in grml small. I am aware that the dnsutils package pulls in a lot of bind libraries that blow up the image, but basic debugging is necessary nevertheless. If a DNS debugging utility is available with less bad dependencies, please go for that one.
Greetings
Marc

**Comment by mika** [comment]
I agree that `dig` is nice to have available on grml-small as well, though it's pulling in dependencies resulting in total disk usage of additional ~41MB. :( Before going that route I'd like to gather more feedback. @formorer @evgeni @jkirk - opinions?

**Comment by evgeni** [comment]
I am not a big grml-small user, but I agree, a system without `dig` is a bad system.
Maybe `drill` (Debian: ldnsutils) has fewer deps?

**Comment by Zugschlus** [comment]
Argl 41 MB is of course _way_ over the top. I wasn't aware it was _this_ bad.

**Comment by Zugschlus** [comment]
@evgeni, drill looks nice, the ldnsutils package dependencies look not remotely as bad.
Can zsh be coaxed into giving a hint towards drill when one types dig or host? Otherwise I think that many people would miss drill being present.

**Comment by evgeni** [comment]
@ft can zsh do something like that? Either on completion or command-not-found?

**Comment by ft** [comment]
We could define a `dig` function on -small systems. And even a `_dig` completion that hints at `drill`.

Those could go into a package that only gets selected on -small, and that would be that. I have to think about how to handle the situation, when a user installs dig on top of a -small system. But it's probably fairly straight forward.

**Comment by mika** [comment]
I just pushed https://github.com/grml/grml-live/commit/38c0449ade8074c05ab8ff5b433f268b232dd73d - @ft - any chance you might help me with the related `dig` function for grml-zshrc (or a separate package)?

**Comment by ft** [comment]
I'll try to take a look the weekend. Of course I lost my train of thought about this in the meantime. ;)

**Comment by mika** [comment]
@ft is this a low-hanging fruit which we might get resolved for the upcoming Grml release? :)

**Comment by ft** [comment]
I think we can. Let me take a look next weekend. Also: When's that release due? :)

**Comment by mika** [comment]
@ft thanks! We're trying to get the 2018.12-rc1 ready for release right now, expected to be released within the next few days (we would like to get it done today, though not yet sure we'll really make it :))
