### ISSUE TITLE
logind issue on grml-small 2017.05

### ISSUE THREAD

**Issue by mika** [grml/grml#64]
grml-small 2017.05 has some issue with booting up, bringing up:

```
Failed to start Login Service.
See 'systemctl status systemd-logind.service' for details.
```

multiple times during bootup, without anything useful within the logs.
This might be https://github.com/systemd/systemd/pull/6164 as pointed out by @fsateler (thx!), we need to verify whether a newer systemd version as the one shipped by Grml 2017.05 (v232-23) indeed fixes this issue.

Reporting to not forget about it and make it visible to other users.

**Comment by fsateler** [comment]
If you determine this fixes the issue I figure https://github.com/systemd/systemd/pull/6164 would be backport material for stretch.

**Comment by mika** [comment]
We don't know which change exactly fixed this issue, but it's no longer visible with current systemd (v239-13).
