### ISSUE TITLE
grml-terminalserver scripts don't work with 2017.05 release

### ISSUE THREAD

**Issue by karlh1** [grml/grml#65]
Hi,

there seem to be multiple issues with the grml-terminalserver scripts in the 2017.05 release. I'm using the grml96-full_2017.05.iso image but the issues might also affect other versions.

1. grml-terminalserver-config fails to determine current ip address and netmask because some functions in /etc/grml/sh-lib expect a deprecated ifconfig output format.
2. grml-terminalserver fails to export the correct nfs shares (the netmask value is missing/empty, e.g. it tries to export /lib/live/mount/medium 192.168.1.0/(ro,...) )
3. grml-terminalserver also fails to start the dhcp server.

After correcting 1. and 2. everything seems to work and I was able to boot a VM via PXE. I didn't investigate into 3. yet because I have a dedicated dhcp server.

**Comment by casualscripter** [comment]
Same problem here.

Changing...

#netGetNetmask()
#[...]
ifconfig "$iface_" | awk '/netmask /{print $4;}'
#[...]

#netGetIp()
#[...]
ifconfig "$iface_" | awk '/inet /{print $2;}'
#[...]

in /etc/grml/sh-lib fixed it for me.

**Comment by casualscripter** [comment]
Okay, my "fix" is working in VirtualBox betreen two VMs (BIOS) but on our new hardware in the course room (physical machines) it is not working (UEFI and BIOS).

**Comment by mika** [comment]
@karlh1 - thanks for your bug report!

I just pushed one bug fix that might be related as well: https://github.com/grml/grml-live/commit/54f19116b7d8df35c0b46c8d1b6da9d29c1307e3
I need to look into all the issues in more details yet.

@casualscripter hm, what exactly is failing with UEFI boot for you?

**Comment by mika** [comment]
This should be fixed with the new version of grml-shlib, thanks for your feedback!
