### ISSUE TITLE
please include mkpasswd in grml-small

### ISSUE THREAD

**Issue by Zugschlus** [grml/grml#66]
Hi,
please include mkpasswd in grml-small. This makes login recovery much easier.
Greetings
Marc

**Comment by mika** [comment]
Are we talking about `/usr/bin/mkpasswd.pl` from Debian package `libstring-mkpasswd-perl`?

**Comment by Zugschlus** [comment]
It surprises me every time, that Debian's mkpasswd is part of the whois package. It's the mkpassword that can generate salted hashes suitable for /etc/shadow.
