### ISSUE TITLE
please include rdnssd and ndisc6 in grml-small

### ISSUE THREAD

**Issue by Zugschlus** [grml/grml#67]
rdnssd is a tool that will listen to DNS server being offered in an IPv6 router anouncement and configure the local system to use the DNS servers included in there. The daemon just needs to be installed and enabled. Without this, an IPv6 only grml system will be with network, but without DNS.
While we're at it, IPv6 is much more easily debugged if ndisc6, a user space tool to send out IPv6 router solicitations and to display the contents of router advertisements received, is included.

**Comment by mika** [comment]
Thanks for the suggestion, the daily ISOs (daily.grml.org) as of tomorrow as well as the upcoming stable releases should ship rdnssd + ndisc6 with grml-small and grml-full.
