### ISSUE TITLE
32 Bit ISO mislabeled as "i586+", requires i686

### ISSUE THREAD

**Issue by rnlf** [grml/grml#68]
I downloaded the current release (2017.5) and tried to boot in on my Pentium MMX (clearly something we would classify as i586), but apparently the Kernel used on the ISO requires cmov, an instruction that was only introduced on the Pentium Pro (which we call i686).

I can understand that people with Pentium MMX and older machines are not the core audience of grml, but you might want to update the download page!

**Comment by mika** [comment]
Thanks for your bug report, I just took care of updating the website accordingly.
