### ISSUE TITLE
RFE: add fsarchiver to grml-small

### ISSUE THREAD

**Issue by marcosfrm** [grml/grml#69]
fsarchiver is small, text only, with few dependencies. grml-small already has all basic filesystems tools (e2fsprogs, xfsprogs, jfsutils, dosfstools, etc) that are required for fsarchiver work.

http://www.fsarchiver.org/
https://github.com/fdupoux/fsarchiver
https://tracker.debian.org/pkg/fsarchiver

**Comment by mika** [comment]
Thanks for the suggestion, the daily ISOs (daily.grml.org) as of tomorrow as well as the upcoming stable releases should ship fsarchiver.

**Comment by marcosfrm** [comment]
Thanks!

Now I realised that btrfs-progs is not present on grml-small. From fsarchiver POV this is not a problem (it does not have hard dependency on mkfs.btrfs). Perhaps if you can put some more kilobytes into grml-small it would be a nice addition for filesystem tasks.

**Comment by mika** [comment]
btrfs-progs would add another 4296kb of additional disk space on grml-small. :-/
Opinions about this, @jkirk @formorer @evgeni?

**Comment by marcosfrm** [comment]
Clarifying: fsarchiver detects at runtime if the needed tools for the **fs being created** are available. If not, it will fail. So you can leave btrfs-progs out if it is too big, only Btrfs support will be lacking in fsarchiver in this case.

**Comment by evgeni** [comment]
@mika well, I guess it boils down to "what is actually *grml-small*?"

a grml version that is…
* … fitting on a 256MiB flash? nope
* … fitting on a 512MiB flash? maybe
* … that is smaller than grml-full? yeah
* … that is quick to download? yeah

none of the maybe/yeah ones are going to be hurt when we add another 4MiB to it.

**Comment by mika** [comment]
Thanks, good point @evgeni 
Also on IRC the opinions were in favor of adding btrfs-progs, so I've done so!
Thanks everyone.
