### ISSUE TITLE
grml-autoconfig: interactive scripts do not work

### ISSUE THREAD

**Issue by marcosfrm** [grml/grml#71]
https://github.com/grml/grml-autoconfig/blob/master/autoconfig.functions#L1497

`config_scripts()` spawns script file with `sh -c`. Should not it be just `sh`? It is a file, not a command sequence.

**Comment by mika** [comment]
Is there anything wrong/not working with it?

I'm not aware of any problems with it and AFAICS it's kind of a trick against having multiple filenames inside $SCRIPTS:

```
% SCRIPTS="./foo ./bar"
% sh -c $SCRIPTS
foo
% sh $SCRIPTS   
sh: 0: Can't open ./foo ./bar
```

@ft - any further comments from your side? :)

**Comment by marcosfrm** [comment]
> Is there anything wrong/not working with it?

I do not know. Came across it when trying to solve the following problem.

On cmdline, I have:

`... autoconfig=FOO scripts=/bar.sh`

`bar.sh` is on FOO's root and is a Bash script (`#!/bin/bash` shebang).

It has some bashisms inside, mainly `read -p`:

```
read -e -p "Bla bla: " -i "initial_value" VAR
```

It fails saying "-p: no coprocess", as probably Zsh is running...

Is there any way to make this script run with Bash?

**Comment by marcosfrm** [comment]
Hmmm, actually **it is** running with Bash, because $BASH_VERSION exists!

How can I make `read -p` work? (the "no coprocess" error must have been my mistake)

**Comment by marcosfrm** [comment]
Sorry flood this bug report. I think `grml-autoconfig.service` lack of `StandardInput=tty` is related.

**Comment by mika** [comment]
If you find a way how to handle that properly let us know.
As a workaround `>/dev/tty1 2>&1 </dev/tty1` around a script should work.

**Comment by marcosfrm** [comment]
I will try add

```
[Service]
StandardInput=tty
TimeoutSec=0
```

to `grml-autoconfig.service`.

**Comment by marcosfrm** [comment]
```
[Service]
ExecStart=/etc/init.d/grml-autoconfig
Type=oneshot
StandardInput=tty
StandardOutput=tty
StandardError=journal+console
TimeoutSec=0
```

works. But every message wrote to stderr by the script is prefixed with "[ time ] grml-autoconfig[PID]:" on the console.

With

```
[Service]
ExecStart=/etc/init.d/grml-autoconfig
Type=oneshot
StandardInput=tty
StandardOutput=tty
TimeoutSec=0
```

(`StandardError=inherit` is assumed)

interactive scripts work fine \o/. I do not know if this configuration can cause problems to other parts of `/etc/init.d/grml-autoconfig` though.

**Comment by mika** [comment]
Nice, thanks for testing and reporting! Definitely worth a try, /cc @jkirk :)

**Comment by marcosfrm** [comment]
When starting services, timeout logic is disabled with `Type=oneshot` (man systemd.service). On shutdown it is probably wise keep the timeout active I think. Hence `TimeoutSec=0` is not required.

Back to the `sh` question, actually `sh -c` is *required*. My scripts stopped working with only `sh`.

**Comment by jkirk** [comment]
@marcosfrm Thank you very much for the investigation. We will have a look into this...

**Comment by marcosfrm** [comment]
Any news? Can I send a pull request?

**Comment by mika** [comment]
Hej, sure - pull requests are always welcome! :)
