### ISSUE TITLE
network boot / toram does not work on hosts with multiple interfaces

### ISSUE THREAD

**Issue by Zugschlus** [grml/grml#73]
Hi,
I am booting grml64-small 2017.05 from network using iPXE and the following configuration:

     echo booting grml64-small 2017.05 amd64 from ${httpbase}
     set serial serial console=ttyS0,115200n8
     kernel ${httpbase}/grml64-small_2017.05/boot/grml64small/vmlinuz quiet lang=de boot=live noquick noeject noprompt bootid=grml64small201705 radeon.modeset=1 keyboard=de fetch=${httpbase}/grml64-small_2017.05/./live/grml64-small/grml64-small.squashfs ethdevice-timeout=30 ${serial}
     initrd ${httpbase}/grml64-small_2017.05/boot/grml64small/initrd.img
     boot

The VM I am trying this on has two network interfaces, the DHCP server being on the first one, and the second one is disconnected. The system ends up sans resolv.conf and unable to resolve the web server to download the squashfs from:

      * Running grml64-small 2017.05 Release Codename Freedatensuppe [2017-05-31]
      * Finished early booting sequence. [ ok ]
      * Searching for GRML file, this might take a few seconds...
     Waiting for ethernet card(s) up... If this fails, maybe the ethernet card is not supported by the kernel      4.9.0-1-grml-amd64?
     Looking for a connected Ethernet interface ... ens3 ? ens7 ?
     Connected ens3 found
     Connected ens7 found
     Using timeout of 30 seconds for network configuration.
     Net: Turning on all device links...
     If you want to boot from a specific device use bootoption ethdevice=...
     Executing ipconfig -t 30 ens3
     IP-Config: ens3 hardware address 52:54:00:98:85:17 mtu 1500 DHCP RARP
     IP-Config: ens3 guessed broadcast address 192.168.188.255
     IP-Config: ens3 complete (dhcp from 192.168.181.161):
      address: 192.168.188.207  broadcast: 192.168.188.255  netmask: 255.255.255.0
      gateway: 192.168.188.254  dns0     : 192.168.181.53   dns1   : 192.168.251.53
      domain : ka51.zugschlus.de
      rootserver: 192.168.181.100 rootpath:
      filename  : undionly.kpxe
     Executing ipconfig -t 30 ens7
     IP-Config: ens7 hardware address 52:54:00:89:fd:0d mtu 1500 DHCP RARP
     IP-Config: no response after 30 secs - giving up
     Creating /etc/resolv.conf
     --2017-09-16 10:59:02--  http://weave.ka51.zugschlus.de/pxe/grml64-small_2017.05/live/grml64-small/grml64-small.squashfs
     Resolving weave.ka51.zugschlus.de (weave.ka51.zugschlus.de)...
     
     BusyBox v1.22.1 (Debian 1:1.22.0-19+b3) built-in shell (ash)
     Enter 'help' for a list of built-in commands.
     
     (initramfs) failed: Connection timed out.
     wget: unable to resolve host address 'weave.ka51.zugschlus.de'
     Unable to find a live file system on the network

Removing the second interface makes the system boot, which is unfortunately not an option for hardware (which might have a different, DHCP-less network on the second interface).

Should grml bother initializing the second interface in the first place if the first one has shown to be the one that the DHCP server is on?

**Comment by mika** [comment]
As stated in your bug report message `If you want to boot from a specific device use bootoption ethdevice=..` does the trick, and as discussed on IRC `ethdevice=eth0` indeed solved your issue.

The network stuff of live-boot-grml would be nice to have improved, the relevant section is at https://github.com/grml/live-boot-grml/blob/master/components/9990-networking.sh#L73 and I'd be more than happy to accept such PRs.

**Comment by mika** [comment]
If anyone comes up with a patch to support detection of a configured interface so the `ethdevice=...` wouldn't be needed I'd be more than happy to accept it. As the initial issue has been resolved and we don't consider working on this in the near future, closing for now.
