### ISSUE TITLE
Notebook should not suspend if lid is closed

### ISSUE THREAD

**Issue by jkirk** [grml/grml#75]
When Grml is booted on a notebook it should not go into suspend when closing the lid.

**Comment by jkirk** [comment]
```sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target```

should do the trick. We should make this default.

**Comment by marcosfrm** [comment]
`HandleLidSwitch=ignore` in `/etc/systemd/logind.conf` is a another (possibly better) option.

**Comment by marcosfrm** [comment]
Is
https://github.com/grml/grml-live/blob/master/etc/grml/fai/config/files/etc/systemd/logind.conf/GRMLBASE
the correct place for this?

**Comment by jkirk** [comment]
Nice. Thank you for bringing this up again.

Yes, this should be the place. Would you like to file a PR for it? Thank you!

**Comment by marcosfrm** [comment]
Done.
