### ISSUE TITLE
grml64-full_testing (64bit) / grml64-full_sid (64bit): sshd fails to start

### ISSUE THREAD

**Issue by sl0n** [grml/grml#80]
When "ssh=mypassword" boot flag is provided, sshd fails to start with the following:

> grml sshd[1845]: Missing privilege separation directory: /run/sshd

Workaround:

> mkdir /run/sshd
> service ssh restart

**Comment by mika** [comment]
Quoting johnLate from IRC:

``
I think RuntimeDirectory=sshd needs to be added to /etc/grml/fai/config/files/etc/systemd/system/ssh.service/GRMLBASE (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=864190)
``
