### ISSUE TITLE
Fails to boot with slow virtual CD-ROM device

### ISSUE THREAD

**Issue by ivan** [grml/grml#83]
I attached `grml64-small_2017.05.iso` to a virtual CD-ROM device using HP iLO, which could read the ISO at ~52KB/s (even though the line was ~200KB/s up).  I booted grml64-small and it looked like the boot process gave up, possibly due to a systemd timeout starting `systemd-logind`:

![grml-small-systemd-logind-timeout](https://user-images.githubusercontent.com/4458/33552542-1f9faf46-d8ed-11e7-9623-27cd9eae3dc1.png)

If I am reading the failure right, it is possible that it would succeed if the systemd service startup timeouts were raised significantly.

As a workaround, I am reminded (thanks jm_) that there is a boot option to read the entire iso into memory first.

**Comment by mika** [comment]
Was able to reproduce this on HP ProLiant DL380 Gen9 system (with grml64-full 2017.05 as virtual drive in iLO4), seems to be related to #64.

I was able to work around this issue via "systemctl daemon-reexec; systemctl restart systemd-logind.service".

**Comment by mika** [comment]
Haven't seen this with current daily ISOs since quite some time anymore, considering this as resolved (at least for current daily ISOs and the upcoming stable release). Please let us know if you should ever explore this again, thanks for the bug report!
