### ISSUE TITLE
Grml 2017.05 fails to mount root on a UEFI system

### ISSUE THREAD

**Issue by gsauthof** [grml/grml#85]
The Grml 2017.05 full 96 image (flashed to a USB stick) fails to boot a Supermicro A2SDi-8C+-HLN4F system. AFAICS, the system is UEFI only and doesn't support legacy boot. It features an Atom C3758 CPU. Secure boot is disabled (default BIOS setting).

The boot fails after the Grml early boot menu, i.e. after the main Grml 64 entry is selected. It fails with some kernel messages:

    VFS: Cannot open root device "(null)" or unknown-block(1,0): error -6
    Please append a correct "root=" boot option: here are the available partitions:
    Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(1,0)

FWIW, a Fedora 27 Live USB stick boots fine.

Both images were written to the USB stick with `dd`.

**Comment by mika** [comment]
Hm, interesting one, never saw that on my own so far :)

Would be interesting to know what drivers are responsible for that, any chance you might give us the output of `uname -a ; lspci -k; lsmod` from a system like the Fedora 27 one that boots on this system?

**Comment by gsauthof** [comment]
Sure¸ below output are from a current Fedora 27 system that is booted from the internal harddisk.

uname:

    uname -a
    Linux xyz.example.org 4.13.16-302.fc27.x86_64 #1 SMP Thu Nov 30 15:33:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

lsmod:

    lsmod
    Module                  Size  Used by
    sha512_ssse3           45056  0
    sha512_generic         16384  1 sha512_ssse3
    vfat                   20480  1
    fat                    65536  1 vfat
    intel_rapl             20480  0
    x86_pkg_temp_thermal    16384  0
    intel_powerclamp       16384  0
    coretemp               16384  0
    kvm_intel             200704  0
    kvm                   585728  1 kvm_intel
    irqbypass              16384  1 kvm
    crct10dif_pclmul       16384  0
    crc32_pclmul           16384  0
    ghash_clmulni_intel    16384  0
    ipmi_ssif              24576  0
    joydev                 20480  0
    ixgbe                 311296  0
    qat_c3xxx              16384  1
    ptp                    20480  1 ixgbe
    synaptics_usb          16384  0
    wdat_wdt               16384  0
    pps_core               20480  1 ptp
    intel_qat             135168  2 qat_c3xxx
    mdio                   16384  1 ixgbe
    dca                    16384  1 ixgbe
    i2c_i801               24576  0
    tpm_tis                16384  0
    authenc                16384  1 intel_qat
    ipmi_si                57344  0
    tpm_tis_core           20480  1 tpm_tis
    ipmi_devintf           20480  0
    tpm                    53248  2 tpm_tis,tpm_tis_core
    i2c_ismt               24576  0
    ipmi_msghandler        45056  3 ipmi_ssif,ipmi_devintf,ipmi_si
    shpchp                 36864  0
    acpi_cpufreq           20480  0
    nfsd                  335872  13
    auth_rpcgss            61440  1 nfsd
    nfs_acl                16384  1 nfsd
    lockd                  90112  1 nfsd
    grace                  16384  2 nfsd,lockd
    sunrpc                331776  17 auth_rpcgss,nfsd,nfs_acl,lockd
    btrfs                1101824  1
    xor                    24576  1 btrfs
    raid1                  40960  2
    raid6_pq              118784  1 btrfs
    i2c_algo_bit           16384  0
    drm_kms_helper        159744  0
    ttm                    94208  0
    drm                   352256  2 ttm,drm_kms_helper
    crc32c_intel           24576  1

lspci:

    00:00.0 Host bridge: Intel Corporation Device 1980 (rev 11)
    	Subsystem: Super Micro Computer Inc Device 0969
    00:04.0 Host bridge: Intel Corporation Device 19a1 (rev 11)
    	Subsystem: Super Micro Computer Inc Device 0969
    00:05.0 Generic system peripheral [0807]: Intel Corporation Device 19a2 (rev 11)
    	Subsystem: Super Micro Computer Inc Device 0969
    00:06.0 PCI bridge: Intel Corporation Device 19a3 (rev 11)
    	Kernel driver in use: pcieport
    	Kernel modules: shpchp
    00:09.0 PCI bridge: Intel Corporation Device 19a4 (rev 11)
    	Kernel driver in use: pcieport
    	Kernel modules: shpchp
    00:10.0 PCI bridge: Intel Corporation Device 19aa (rev 11)
    	Kernel driver in use: pcieport
    	Kernel modules: shpchp
    00:11.0 PCI bridge: Intel Corporation Device 19ab (rev 11)
    	Kernel driver in use: pcieport
    	Kernel modules: shpchp
    00:12.0 System peripheral: Intel Corporation DNV SMBus Contoller - Host (rev 11)
    	Subsystem: Super Micro Computer Inc Device 0969
    	Kernel driver in use: ismt_smbus
    	Kernel modules: i2c_ismt
    00:13.0 SATA controller: Intel Corporation DNV SATA Controller 0 (rev 11)
    	Subsystem: Super Micro Computer Inc Device 0969
    	Kernel driver in use: ahci
    00:14.0 SATA controller: Intel Corporation DNV SATA Controller 1 (rev 11)
    	Subsystem: Super Micro Computer Inc Device 0969
    	Kernel driver in use: ahci
    00:15.0 USB controller: Intel Corporation Device 19d0 (rev 11)
    	Subsystem: Super Micro Computer Inc Device 0969
    	Kernel driver in use: xhci_hcd
    00:16.0 PCI bridge: Intel Corporation Device 19d1 (rev 11)
    	Kernel driver in use: pcieport
    	Kernel modules: shpchp
    00:17.0 PCI bridge: Intel Corporation Device 19d2 (rev 11)
    	Kernel driver in use: pcieport
    	Kernel modules: shpchp
    00:18.0 Communication controller: Intel Corporation Device 19d3 (rev 11)
    	Subsystem: Super Micro Computer Inc Device 0969
    00:1f.0 ISA bridge: Intel Corporation DNV LPC or eSPI (rev 11)
    	Subsystem: Super Micro Computer Inc Device 0969
    00:1f.2 Memory controller: Intel Corporation Device 19de (rev 11)
    	Subsystem: Super Micro Computer Inc Device 0969
    00:1f.4 SMBus: Intel Corporation DNV SMBus controller (rev 11)
    	Subsystem: Super Micro Computer Inc Device 0969
    	Kernel driver in use: i801_smbus
    	Kernel modules: i2c_i801
    00:1f.5 Serial bus controller [0c80]: Intel Corporation DNV SPI Controller (rev 11)
    	Subsystem: Super Micro Computer Inc Device 0969
    01:00.0 Co-processor: Intel Corporation Device 19e2 (rev 11)
    	Subsystem: Intel Corporation Device 0000
    	Kernel driver in use: c3xxx
    	Kernel modules: qat_c3xxx
    04:00.0 PCI bridge: ASPEED Technology, Inc. AST1150 PCI-to-PCI Bridge (rev 03)
    	Kernel modules: shpchp
    05:00.0 VGA compatible controller: ASPEED Technology, Inc. ASPEED Graphics Family (rev 30)
    	Subsystem: Super Micro Computer Inc Device 0969
    	Kernel modules: ast
    06:00.0 Ethernet controller: Intel Corporation Ethernet Connection X553 1GbE (rev 11)
    	Subsystem: Super Micro Computer Inc Device 15e4
    	Kernel driver in use: ixgbe
    	Kernel modules: ixgbe
    06:00.1 Ethernet controller: Intel Corporation Ethernet Connection X553 1GbE (rev 11)
    	Subsystem: Super Micro Computer Inc Device 15e4
    	Kernel driver in use: ixgbe
    	Kernel modules: ixgbe
    07:00.0 Ethernet controller: Intel Corporation Ethernet Connection X553 1GbE (rev 11)
    	Subsystem: Super Micro Computer Inc Device 15e4
    	Kernel driver in use: ixgbe
    	Kernel modules: ixgbe
    07:00.1 Ethernet controller: Intel Corporation Ethernet Connection X553 1GbE (rev 11)
    	Subsystem: Super Micro Computer Inc Device 15e4
    	Kernel driver in use: ixgbe
    	Kernel modules: ixgbe

**Comment by mika** [comment]
@gsauthof we had some fixes and improvements related to EFI booting in our 2018.12-rc1 release. Could you please give this a try and let us know whether this fixes your issue? (The 2018.12 stable release will hit the mirrors as well, so if you're reading this and 2018.12 is available use the stable release of course :))

**Comment by gsauthof** [comment]
I've just tested grml96-full_2018.12.iso and now it fails differently:

After selecting the USB stick in the firmware bootmenu and hitting return I see a blank screen for ~ 1 second and then the bootmenu is displayed again.

Basically it looks like the grml bootloader immediately exits.

I can also reproduce this issue on a Thinkpad x220t - when it's switched to uefi-only boot. That means it has the same failure mode as described above.

When switched to Legacy+UEFI (legacy first), Grml boots fine on that Thinkpad.

(Using the same stick in all cases.)

**Comment by mika** [comment]
Uff, this sounds like a problem with the EFI firmware then. :-/ Just to clarify, you're using the most recent BIOS/EFI/... firmware version that's available for your x220t, @gsauthof?

**Comment by gsauthof** [comment]
I can reproduce this on the x220t and the Supermicro A2SDi-8C+-HLN4F. The failure experience is the same. The firmware version on the Supermicro is definitely the latest one. I don't have the x220t accessible  right now, but it should have received some firmware updates over the years. Also, I have a USB stick that contains a Fedora 29 installation and I can boot it fine on the x220t - in uefi-only mode.

I can't even boot the Grml stick (grml96-full_2018.12.iso) in uefi-only QEMU. That means this fails to boot grml:

    cp /usr/share/edk2/ovmf/OVMF_VARS.fd .
    qemu-system-x86_64 -enable-kvm -m 2G -drive \
        if=pflash,format=raw,readonly,file=/usr/share/edk2/ovmf/OVMF_CODE.fd  \
        -drive if=pflash,format=raw,file=OVMF_VARS.fd  -hda /dev/sdb

While this works:

    qemu-system-x86_64 -enable-kvm -m 2G  -hda /dev/sdb

**Comment by mika** [comment]
@gsauthof I looked into this and provided bugfixes for the grml96 toolchain so EFI boot (should) work again (with 64bit!) on grml96, could you please check whether your issue is fixed with Grml release 2020.06?

**Comment by mika** [comment]
The grml96 ISOs of the Grml 2020.06 release are known to be working fine under EFI boot in 64bit mode, so I'm closing this issue. If anyone should still notice any issues please let me/us know!

**Comment by gsauthof** [comment]
Now I had a chance to try a fresh grml96 2020.06 on an UEFI system (Thinkpad) and there it boots fine (`/sys/firmware/efi` is also available after boot, as expected).
