### ISSUE TITLE
grml-lock using wrong physlock option

### ISSUE THREAD

**Issue by maximebuy** [grml/grml#87]
script `/usr/bin/grml-lock` call the cmd `physlock` as below:
```bash
lock_desktop() {
  sudo physlock -u "$USER"
}
```
`physlock` doesn't have `-u` option anymore. The following output after run `grm-lock`:
```bash
physlock: invalid option -- 'u'
usage: physlock [-dhLlmsv] [-p MSG]
```

**Comment by mika** [comment]
Thanks, this should be fixed with the upcoming release now!
