### ISSUE TITLE
[grml-zsh-config] sudo error with aliases defined using the "command" shell builtin

### ISSUE THREAD

**Issue by neitsab** [grml/grml#94]
Hi, on Arch Linux when using an alias defined in `/etc/zsh/zshrc` using the `command` builtin via sudo (e.g. la), we receive the error message`sudo: la: command not found`. However once in a root shell via `sudo -i` the aliases work properly.

Additional info:
* package version(s): 0.14.3-1 + zsh 5.5.1
* config and/or log files etc.
Vanilla config files, no `~/.zshrc{,.pre,.local}` in my user's or root's home directory and sudoers only contain `myusername ALL=(ALL) ALL`.

Affected aliases:
```
% grep "=\"command " /etc/zsh/zshrc
alias ls="command ls ${ls_options:+${ls_options[*]}}"
alias la="command ls -la ${ls_options:+${ls_options[*]}}"
alias ll="command ls -l ${ls_options:+${ls_options[*]}}"
alias lh="command ls -hAl ${ls_options:+${ls_options[*]}}"
alias l="command ls -l ${ls_options:+${ls_options[*]}}"
alias dir="command ls -lSrah"
alias lsbig="command ls -flh *(.OL[1,10])"
alias lsnew="command ls -rtlh *(D.om[1,10])"
alias lsold="command ls -rtlh *(D.Om[1,10])"
alias lssmall="command ls -Srl *(.oL[1,10])"
alias lsnewdir="command ls -rthdl *(/om[1,10]) .*(D/om[1,10])"
alias lsolddir="command ls -rthdl *(/Om[1,10]) .*(D/Om[1,10])"
```

Steps to reproduce:

```
$ sudo pacman -S zsh grml-zsh-config
$ chsh -s /usr/bin/zsh
$ sudo chsh -s /usr/bin/zsh root
$ zsh
% ll
<correct output>
% sudo la
sudo: la: command not found
% sudo -i
# la
<correct output>
```

([Distribution bug report](https://bugs.archlinux.org/task/58360))

**Comment by mika** [comment]
Hm, I don't understand why this should work via `sudo la` at all (unless it's run via an interactive/login shell):

```
mika@heart ~ % bash
mika@heart:~$ alias ll
bash: alias: ll: not found
mika@heart:~$ alias ll="ls -la"
mika@heart:~$ sudo ll
[sudo] password for mika: 
sudo: ll: command not found

mika@heart:~$ zsh -f
heart% alias ll
heart% alias ll='ls -la'
heart% sudo ll
sudo: ll: command not found
```

@ft - any idea what's going on here?

**Comment by ft** [comment]
No. Aliases are only expanded in command position (unless they are global aliases, which our setup does not use). Thus, the aliases are not subject to expansion in "sudo COMMAND".

You could try and "set -x" and then issue the failing command and we'll take a look at the trace.

**Comment by ft** [comment]
Wait a minute? Upon re-reading the report, it sounds like you're not aware that in "sudo CMD" the string CMD is not subject to alias expansion. That's absolutely expected behaviour.

**Comment by mika** [comment]
@ft, jepp, that's exactly what I as thinking of, what's confusing me though is the comment in https://bugs.archlinux.org/task/58360#comment168846 which says that it works if they remove the "command" within the alias setup. o_O :)

**Comment by jkirk** [comment]
It seems that we can not do anything about this issue. Closing.
