### ISSUE TITLE
External USB3 SCSI drives are stopped, thwart boot....

### ISSUE THREAD

**Issue by behoffski** [grml/grml#98]
[This is possibly a feature request; I know little about systemd.]

I currently do backups to a set of external USB 2TB drives.  The drive is partitioned into two EXT-FS sections, with the first being a small (boot) partition, and the second being the main backup storage.  (Because of my tape-driven early employment days, I use three hard disk drives in rotation: grandfather-father-son.)

The small partition is roughly 2GiB; it may be 5GiB in some experimental situations on drives where I'm playing with other distro's live-boot-DVD facilities.  The small partition has the 64-bit filesystem option switched off ("-O^64bit"), in order to be compatible with syslinux/extlinux, as otherwise booting fails very early with the error message "Failed to load ldlinux.c32".

I love using grml for this backup setup; I have prepared some tailoring scripts that load Lua and LuaRocks, so that I can write scripts to build a database of machine characteristics (e.g. partition UUIDs), and can manage backup size issues:  The presence of multiple generations of backups for a machine may consume so much space that older images need to be pruned.

This set-up works very well if I boot GRML off of an USB key, and plug the hard drive into another (USB3) port... but I just plug in the hard drive, then extlinux correctly gives me the GRML splash screen, and presents the starting menu.  However, at some point (I assume after loading the kernel itself), I notice that a "SCSI STOP" command must have been sent to the hard drive, as it is no longer spinning, and the access LED is a low-cadence signal, showing "spun-down" or perhaps, equally, "powered-down" mode.

This is a fatal state for the drive to be in, for when the bootstrap process says "Looking for grml.sh", it tries for 30-50 seconds before giving up, saying it cannot find the boot media.

So, at present, I boot off of a solid-state USB key (e.g. 8 GiB etc), and only plug in the hard drive after the time when I suspect that the power-down commands have been issued.  As this is an easy procedure/workaround, I believe that this issue is best treated as a feature request.  However, there is a slight chance that this situation may  be involved in some issues reported by others.

**Comment by mika** [comment]
Uff, this sounds strange, I've never seen such an issue myself so far. We have to identify which component is responsible for this behavior. As a starting point I'd recommend booting with boot option `break=init`. You'll get a busybox shell within the initramfs with this bootoption, straight before the init system (systemd) kicks in. You can check whether the disk is powered down then already (or gets powered down soon after).

**Comment by behoffski** [comment]
[FYI:  I'm still working with GRML 2017.11; let me know if I should
try a development release, as obviously much, including the kernel,
has changed since that time.]

Okay, I've added "break=init" to the kernel boot and "append" lines
within the bootloader (Grub2, I think).  I do get busybox output:

     BusyBox v1.22.1
     (initramfs) Unable to find a medium containing a live filesystem.

Looking carefully at the screen and monitoring the drive's power
status, I believe that the drive is placed on standby shortly before
the kernel clears the screen and writes the icons for the CPUs at
the top of the display.

"ls" within BusyBox shows me //live/grml_full_64 (I think), but this
directory is empty.  //live/medium is also empty.

---------

I noted a power-related directive in the boot options:

         apm=power-off

Since I'm on a Gentoo system, the kernel sources were easily at
hand.

I've tried adding "apm=idle-threshold=100" (tell apm to never
regard the system as being idle), and have tried booting with
this option, both with and without the "power-off" directive
above (just in case there was interaction/interference between
the different apm directives).

The "power-off" directive should not have affected boot, only
shutdown.  (The apm options are documented in the kernel at:
         arch/x86/kernel/apm_32.c
.)

None of these attempts at playing with apm fixed the boot
process, sigh.

-- sur-behoffski (Brenton Hoff)

**Comment by behoffski** [comment]
[First of all, previous efforts were with 2017.05; I mistakenly
said 2017.11, but obviously that was wrong, sorry.]

I've just downloaded and tried the latest "testing" build of GRML-64-full
(2018-12-16 -- build 2610) -- but have not seen any change in behaviour:
The Western Digital 2TB USB3 drive, with a 5GiB "GRML" bootable partition
1, and the remainder (primary partition 2) as a "backup images" partition,
can be selected for boot from the BIOS, syslinux offers the
GRML64-latest-testing image... the drive flashes as the kernel is loaded,
but enters offline/power-down mode in what looks to be the same fashion
as when working with 2017.05.

-- s-b etc etc

**Comment by jkirk** [comment]
@behoffski Could you please test this with a current [Grml Daily ISO](https://grml.org/daily/) and check if this issue is still present. Thx.

**Comment by behoffski** [comment]
Have just downloaded and tried Daily build 2914, and the issue no longer appears (tried two machines: an i7 laptop, plus a Xeon workstation).  Marking this issue as Closed (from my point of view), although a stronger test across wider range of architectures/BIOSes/USB external drives woul be nice.
